# Generated by Django 4.2.7 on 2026-01-22 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('order_created', 'Užsakymas sukurtas'), ('order_updated', 'Užsakymas atnaujintas'), ('order_deleted', 'Užsakymas ištrintas'), ('order_status_changed', 'Užsakymo būsena pakeista'), ('sales_invoice_created', 'Pardavimo sąskaita sukurta'), ('sales_invoice_updated', 'Pardavimo sąskaita atnaujinta'), ('sales_invoice_deleted', 'Pardavimo sąskaita ištrinta'), ('purchase_invoice_created', 'Pirkimo sąskaita sukurta'), ('purchase_invoice_updated', 'Pirkimo sąskaita atnaujinta'), ('purchase_invoice_deleted', 'Pirkimo sąskaita ištrinta'), ('payment_added', 'Mokėjimas pridėtas'), ('payment_deleted', 'Mokėjimas ištrintas'), ('payment_status_changed', 'Mokėjimo būsena pakeista'), ('partner_created', 'Partneris sukurtas'), ('partner_updated', 'Partneris atnaujintas'), ('partner_deleted', 'Partneris ištrintas'), ('settings_updated', 'Nustatymai atnaujinti'), ('file_uploaded', 'Failas įkeltas'), ('file_deleted', 'Failas ištrintas'), ('email_sent', 'El. laiškas išsiųstas'), ('custom', 'Kitas veiksmas')], max_length=50, verbose_name='Veiksmo tipas')),
                ('description', models.TextField(help_text='Detalus veiksmo aprašymas', verbose_name='Aprašymas')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Susijęs objektas (ID)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Papildomi duomenys JSON formatu (pvz., senos/naujos reikšmės)', verbose_name='Papildoma informacija')),
                ('user_name', models.CharField(blank=True, help_text='Išsaugomas vartotojo vardas, jei vartotojas bus ištrintas', max_length=255, verbose_name='Vartotojo vardas')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP adresas')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Sukurta')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Susijęs objektas (tipas)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Vartotojas')),
            ],
            options={
                'verbose_name': 'Veiksmų istorija',
                'verbose_name_plural': 'Veiksmų istorija',
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='activity_lo_created_d8c226_idx'), models.Index(fields=['action_type', '-created_at'], name='activity_lo_action__5e24c2_idx'), models.Index(fields=['content_type', 'object_id'], name='activity_lo_content_edc5bf_idx'), models.Index(fields=['user', '-created_at'], name='activity_lo_user_id_b8c999_idx')],
            },
        ),
    ]
