# Generated by Django 4.2.7 on 2026-01-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_add_activity_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('order_created', 'Užsakymas sukurtas'), ('order_updated', 'Užsakymas atnaujintas'), ('order_deleted', 'Užsakymas ištrintas'), ('order_status_changed', 'Užsakymo būsena pakeista'), ('sales_invoice_created', 'Pardavimo sąskaita sukurta'), ('sales_invoice_updated', 'Pardavimo sąskaita atnaujinta'), ('sales_invoice_deleted', 'Pardavimo sąskaita ištrinta'), ('purchase_invoice_created', 'Pirkimo sąskaita sukurta'), ('purchase_invoice_updated', 'Pirkimo sąskaita atnaujinta'), ('purchase_invoice_deleted', 'Pirkimo sąskaita ištrinta'), ('payment_added', 'Mokėjimas pridėtas'), ('payment_deleted', 'Mokėjimas ištrintas'), ('payment_status_changed', 'Mokėjimo būsena pakeista'), ('partner_created', 'Partneris sukurtas'), ('partner_updated', 'Partneris atnaujintas'), ('partner_deleted', 'Partneris ištrintas'), ('invoice_status_changed', 'Sąskaitos būsena pakeista'), ('carrier_status_changed', 'Vežėjo būsena pakeista'), ('cost_status_changed', 'Išlaidų būsena pakeista'), ('settings_updated', 'Nustatymai atnaujinti'), ('file_uploaded', 'Failas įkeltas'), ('file_deleted', 'Failas ištrintas'), ('email_sent', 'El. laiškas išsiųstas'), ('custom', 'Kitas veiksmas')], max_length=50, verbose_name='Veiksmo tipas'),
        ),
        migrations.CreateModel(
            name='StatusTransitionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('order', 'Užsakymas'), ('sales_invoice', 'Pardavimo sąskaita'), ('purchase_invoice', 'Pirkimo sąskaita'), ('order_carrier', 'Užsakymo vežėjas'), ('order_cost', 'Užsakymo išlaida')], db_index=True, max_length=30, verbose_name='Objekto tipas')),
                ('current_status', models.CharField(db_index=True, max_length=50, verbose_name='Dabartinis statusas')),
                ('allowed_next_statuses', models.JSONField(default=list, help_text='JSON masyvas su leistinų statusų reikšmėmis', verbose_name='Leistini kiti statusai')),
                ('is_active', models.BooleanField(default=True, help_text='Jei neaktyvus, taisyklė nebus naudojama', verbose_name='Aktyvus')),
                ('order', models.IntegerField(default=0, help_text='Taisyklių tvarka (mažesnis skaičius = aukščiau)', verbose_name='Eiliškumas')),
                ('description', models.TextField(blank=True, help_text='Papildomas taisyklės aprašymas', verbose_name='Aprašymas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atnaujinta')),
            ],
            options={
                'verbose_name': 'Statusų perėjimo taisyklė',
                'verbose_name_plural': 'Statusų perėjimo taisyklės',
                'db_table': 'status_transition_rules',
                'ordering': ['entity_type', 'order', 'current_status'],
                'indexes': [models.Index(fields=['entity_type', 'current_status'], name='status_tran_entity__4fcb40_idx'), models.Index(fields=['is_active', 'entity_type'], name='status_tran_is_acti_f994b9_idx')],
                'unique_together': {('entity_type', 'current_status')},
            },
        ),
    ]
