# Generated by Django 4.2.7 on 2026-02-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_create_default_status_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('order_created', 'Užsakymas sukurtas'), ('order_updated', 'Užsakymas atnaujintas'), ('order_deleted', 'Užsakymas ištrintas'), ('order_status_changed', 'Užsakymo būsena pakeista'), ('order_field_updated', 'Užsakymo laukas pakeistas'), ('sales_invoice_created', 'Pardavimo sąskaita sukurta'), ('sales_invoice_updated', 'Pardavimo sąskaita atnaujinta'), ('sales_invoice_deleted', 'Pardavimo sąskaita ištrinta'), ('purchase_invoice_created', 'Pirkimo sąskaita sukurta'), ('purchase_invoice_updated', 'Pirkimo sąskaita atnaujinta'), ('purchase_invoice_deleted', 'Pirkimo sąskaita ištrinta'), ('payment_added', 'Mokėjimas pridėtas'), ('payment_deleted', 'Mokėjimas ištrintas'), ('payment_status_changed', 'Mokėjimo būsena pakeista'), ('partner_created', 'Partneris sukurtas'), ('partner_updated', 'Partneris atnaujintas'), ('partner_deleted', 'Partneris ištrintas'), ('invoice_status_changed', 'Sąskaitos būsena pakeista'), ('carrier_status_changed', 'Vežėjo būsena pakeista'), ('cost_status_changed', 'Išlaidų būsena pakeista'), ('settings_updated', 'Nustatymai atnaujinti'), ('file_uploaded', 'Failas įkeltas'), ('file_deleted', 'Failas ištrintas'), ('email_sent', 'El. laiškas išsiųstas'), ('custom', 'Kitas veiksmas')], max_length=50, verbose_name='Veiksmo tipas'),
        ),
    ]
