# Generated by Django 4.2.7 on 2025-11-06 13:28

import apps.expenses.models
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Pavadinimas')),
                ('description', models.TextField(blank=True, verbose_name='Aprašymas')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktyvi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Išlaidų kategorija',
                'verbose_name_plural': 'Išlaidų kategorijos',
                'db_table': 'expense_categories_v2',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Pavadinimas')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50, unique=True, verbose_name='Įmonės kodas')),
                ('vat_code', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='PVM kodas')),
                ('address', models.TextField(blank=True, verbose_name='Adresas')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefonas')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='El. paštas')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='Kontaktinis asmuo')),
                ('payment_term_days', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Atsiskaitymo terminas (dienos)')),
                ('status', models.CharField(choices=[('active', 'Aktyvus'), ('blocked', 'Užblokuotas')], db_index=True, default='active', max_length=20, verbose_name='Būsena')),
                ('notes', models.TextField(blank=True, verbose_name='Pastabos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Išlaidų tiekėjas',
                'verbose_name_plural': 'Išlaidų tiekėjai',
                'db_table': 'expense_suppliers',
                'indexes': [models.Index(fields=['name'], name='expense_sup_name_e24712_idx'), models.Index(fields=['code'], name='expense_sup_code_c091c6_idx'), models.Index(fields=['status'], name='expense_sup_status_4b673a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExpenseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=100, verbose_name='Sąskaitos numeris')),
                ('amount_net', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Suma be PVM')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='PVM tarifas (%)')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='PVM suma')),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Bendra suma su PVM')),
                ('issue_date', models.DateField(verbose_name='Išrašymo data')),
                ('due_date', models.DateField(verbose_name='Apmokėjimo terminas')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Apmokėjimo data')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Neapmokėta'), ('paid', 'Apmokėta'), ('overdue', 'Vėluoja'), ('partially_paid', 'Dalinis apmokėjimas')], db_index=True, default='unpaid', max_length=20, verbose_name='Mokėjimo statusas')),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to=apps.expenses.models.expense_invoice_file_path, verbose_name='Sąskaitos failas (PDF)')),
                ('notes', models.TextField(blank=True, verbose_name='Pastabos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='expenses.expensecategory', verbose_name='Kategorija')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='expenses.expensesupplier', verbose_name='Tiekėjas')),
            ],
            options={
                'verbose_name': 'Išlaidų sąskaita',
                'verbose_name_plural': 'Išlaidų sąskaitos',
                'db_table': 'expense_invoices',
                'ordering': ['-issue_date', '-created_at'],
                'indexes': [models.Index(fields=['invoice_number'], name='expense_inv_invoice_675160_idx'), models.Index(fields=['supplier'], name='expense_inv_supplie_3fbc77_idx'), models.Index(fields=['category'], name='expense_inv_categor_c5b464_idx'), models.Index(fields=['payment_status'], name='expense_inv_payment_fc1532_idx'), models.Index(fields=['issue_date'], name='expense_inv_issue_d_f3e06e_idx'), models.Index(fields=['due_date'], name='expense_inv_due_dat_26df85_idx')],
            },
        ),
    ]
