# Generated by Django 4.2.7 on 2025-11-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseinvoice',
            name='currency',
            field=models.CharField(default='EUR', max_length=3, verbose_name='Valiuta'),
        ),
        migrations.AddField(
            model_name='expenseinvoice',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, verbose_name='Apmokėjimo būdas'),
        ),
        migrations.AddField(
            model_name='expensesupplier',
            name='bank_account',
            field=models.CharField(blank=True, max_length=100, verbose_name='Banko sąskaita'),
        ),
        migrations.AlterField(
            model_name='expenseinvoice',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Apmokėjimo terminas'),
        ),
    ]
