# Generated by Django 4.2.7 on 2025-10-29 13:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('transport', 'Transportas'), ('logistics', 'Logistika'), ('other', 'Kita')], default='transport', max_length=20, verbose_name='Užsakymo tipas')),
                ('status', models.CharField(choices=[('new', 'Naujas'), ('assigned', 'Priskirtas'), ('executing', 'Vykdomas'), ('waiting_for_docs', 'Laukiama Dokumentų'), ('finished', 'Baigtas (Sąskaitos Išrašymo Galima)'), ('canceled', 'Atšauktas')], db_index=True, default='new', max_length=30, verbose_name='Būsena')),
                ('price_net', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Kaina be PVM')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='PVM tarifas (%)')),
                ('route_from', models.CharField(max_length=255, verbose_name='Maršrutas iš')),
                ('route_to', models.CharField(max_length=255, verbose_name='Maršrutas į')),
                ('loading_date', models.DateTimeField(blank=True, null=True, verbose_name='Pakrovimo data')),
                ('unloading_date', models.DateTimeField(blank=True, null=True, verbose_name='Iškrovimo data')),
                ('notes', models.TextField(blank=True, verbose_name='Pastabos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Užsakymas',
                'verbose_name_plural': 'Užsakymai',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=30, verbose_name='Sena būsena')),
                ('new_status', models.CharField(max_length=30, verbose_name='Nauja būsena')),
                ('notes', models.TextField(blank=True, verbose_name='Pastabos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Užsakymo būsenos istorija',
                'verbose_name_plural': 'Užsakymų būsenų istorijos',
                'db_table': 'order_status_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
