# Generated by Django 4.2.7 on 2025-10-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.CharField(blank=True, help_text='Vežėjo pavadinimas arba kontaktinė informacija', max_length=255, verbose_name='Vežėjas'),
        ),
    ]
