# Generated by Django 4.2.7 on 2025-10-29 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
        ('orders', '0004_alter_order_carrier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrier_orders', to='partners.partner', verbose_name='Vežėjas'),
        ),
    ]
