# Generated by Django 4.2.7 on 2025-10-29 15:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_carrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carrier_invoice_issued',
            field=models.BooleanField(default=False, verbose_name='Išrašyta sąskaita vežėjui'),
        ),
        migrations.AddField(
            model_name='order',
            name='carrier_invoice_paid',
            field=models.BooleanField(default=False, verbose_name='Apmokėta sąskaita vežėjui'),
        ),
        migrations.AddField(
            model_name='order',
            name='carrier_invoice_received',
            field=models.BooleanField(default=False, verbose_name='Gauta sąskaita nuo vežėjo'),
        ),
        migrations.AddField(
            model_name='order',
            name='carrier_price_net',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Kaina vežėjui be PVM'),
        ),
        migrations.AddField(
            model_name='order',
            name='client_invoice_issued',
            field=models.BooleanField(default=False, verbose_name='Išrašyta sąskaita klientui'),
        ),
        migrations.AddField(
            model_name='order',
            name='client_invoice_paid',
            field=models.BooleanField(default=False, verbose_name='Apmokėta sąskaita klientui'),
        ),
        migrations.AddField(
            model_name='order',
            name='client_invoice_received',
            field=models.BooleanField(default=False, verbose_name='Gauta sąskaita nuo kliento'),
        ),
        migrations.AddField(
            model_name='order',
            name='client_price_net',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Kaina klientui be PVM'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_net',
            field=models.DecimalField(decimal_places=2, help_text='Bazinė kaina (naudojama palaikomajam skyriui)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Kaina be PVM'),
        ),
    ]
