# Generated by Django 4.2.7 on 2025-10-29 15:50

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
        ('orders', '0006_order_carrier_invoice_issued_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCarrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_type', models.CharField(choices=[('carrier', 'Vežėjas'), ('warehouse', 'Sandėlys')], default='carrier', max_length=20, verbose_name='Tipas')),
                ('sequence_order', models.IntegerField(default=0, help_text='Nustato tvarką, kurią vežėjai/sandėliai yra naudojami', verbose_name='Eiliškumas')),
                ('price_net', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Kaina be PVM')),
                ('invoice_issued', models.BooleanField(default=False, verbose_name='Išrašyta sąskaita')),
                ('invoice_received', models.BooleanField(default=False, verbose_name='Gauta sąskaita')),
                ('invoice_paid', models.BooleanField(default=False, verbose_name='Apmokėta sąskaita')),
                ('notes', models.TextField(blank=True, verbose_name='Pastabos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carriers', to='orders.order', verbose_name='Užsakymas')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_carrier_entries', to='partners.partner', verbose_name='Partneris')),
            ],
            options={
                'verbose_name': 'Užsakymo vežėjas/sandėlys',
                'verbose_name_plural': 'Užsakymo vežėjai/sandėliai',
                'db_table': 'order_carriers',
                'ordering': ['order', 'sequence_order'],
                'indexes': [models.Index(fields=['order', 'sequence_order'], name='order_carri_order_i_3d65cf_idx')],
            },
        ),
    ]
