# Generated by Django 4.2.7 on 2025-10-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_ordercarrier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='carrier_invoice_issued',
        ),
        migrations.RemoveField(
            model_name='order',
            name='carrier_invoice_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='carrier_invoice_received',
        ),
        migrations.RemoveField(
            model_name='order',
            name='client_invoice_paid',
        ),
        migrations.RemoveField(
            model_name='ordercarrier',
            name='invoice_paid',
        ),
        migrations.AddField(
            model_name='order',
            name='client_payment_status',
            field=models.CharField(choices=[('not_paid', 'Neapmokėta'), ('partially_paid', 'Dalinai apmokėta'), ('paid', 'Apmokėta')], default='not_paid', max_length=20, verbose_name='Kliento mokėjimo būklė'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Užsakymo data'),
        ),
        migrations.AddField(
            model_name='ordercarrier',
            name='loading_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pakrovimo data'),
        ),
        migrations.AddField(
            model_name='ordercarrier',
            name='payment_status',
            field=models.CharField(choices=[('not_paid', 'Neapmokėta'), ('partially_paid', 'Dalinai apmokėta'), ('paid', 'Apmokėta')], default='not_paid', max_length=20, verbose_name='Mokėjimo būklė'),
        ),
        migrations.AddField(
            model_name='ordercarrier',
            name='route_from',
            field=models.CharField(blank=True, max_length=255, verbose_name='Maršrutas iš'),
        ),
        migrations.AddField(
            model_name='ordercarrier',
            name='route_to',
            field=models.CharField(blank=True, max_length=255, verbose_name='Maršrutas į'),
        ),
        migrations.AddField(
            model_name='ordercarrier',
            name='status',
            field=models.CharField(choices=[('new', 'Naujas'), ('in_progress', 'Vykdomas'), ('completed', 'Baigtas'), ('cancelled', 'Atšauktas')], default='new', max_length=20, verbose_name='Vežimo/sandėlio būklė'),
        ),
        migrations.AddField(
            model_name='ordercarrier',
            name='unloading_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Iškrovimo data'),
        ),
    ]
