# Generated by Django 4.2.7 on 2025-10-29 16:52

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_carrier_invoice_issued_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='carrier_price_net',
        ),
        migrations.AddField(
            model_name='order',
            name='my_price_net',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Mano kaina be PVM'),
        ),
        migrations.AddField(
            model_name='order',
            name='other_costs',
            field=models.JSONField(blank=True, default=list, help_text='JSON masyvas su aprašymais ir sumomis, pvz: [{"description": "Draudimas", "amount": 50.00}]', verbose_name='Kitos išlaidos'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_price_net',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Automatiškai apskaičiuojama: Pervežimo/sandėliavimo kaina + Mano kaina + Kitos išlaidos', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Kaina klientui be PVM'),
        ),
    ]
