# Generated by Django 4.2.7 on 2025-10-29 17:12

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_order_carrier_price_net_order_my_price_net_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fragile',
            field=models.BooleanField(default=False, verbose_name='Trapus'),
        ),
        migrations.AddField(
            model_name='order',
            name='hazardous',
            field=models.BooleanField(default=False, verbose_name='Pavojingas'),
        ),
        migrations.AddField(
            model_name='order',
            name='height_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Aukštis (m)'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_palletized',
            field=models.BooleanField(default=False, verbose_name='Paletemis'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_partial',
            field=models.BooleanField(default=False, verbose_name='Dalinis krovinys'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_stackable',
            field=models.BooleanField(default=False, verbose_name='Stabeliuojamas'),
        ),
        migrations.AddField(
            model_name='order',
            name='ldm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='LDM'),
        ),
        migrations.AddField(
            model_name='order',
            name='length_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Ilgis (m)'),
        ),
        migrations.AddField(
            model_name='order',
            name='requires_crane',
            field=models.BooleanField(default=False, verbose_name='Reikalingas kranas'),
        ),
        migrations.AddField(
            model_name='order',
            name='requires_forklift',
            field=models.BooleanField(default=False, verbose_name='Reikalingas keltuvas'),
        ),
        migrations.AddField(
            model_name='order',
            name='requires_permit',
            field=models.BooleanField(default=False, verbose_name='Reikalingas leidimas'),
        ),
        migrations.AddField(
            model_name='order',
            name='requires_special_equipment',
            field=models.BooleanField(default=False, verbose_name='Reikalinga speciali įranga'),
        ),
        migrations.AddField(
            model_name='order',
            name='temperature_controlled',
            field=models.BooleanField(default=False, verbose_name='Temperatūros kontrolė'),
        ),
        migrations.AddField(
            model_name='order',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('truck', 'Sunkvežimis'), ('trailer', 'Priekaba'), ('van', 'Furgonas'), ('refrigerator', 'Šaldiklis'), ('tanker', 'Cisterna'), ('flatbed', 'Plokščiaplatformis'), ('other', 'Kitas')], max_length=20, null=True, verbose_name='Mašinos tipas'),
        ),
        migrations.AddField(
            model_name='order',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Svoris (kg)'),
        ),
        migrations.AddField(
            model_name='order',
            name='width_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Plotis (m)'),
        ),
    ]
