# Generated by Django 4.2.7 on 2025-10-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_fragile_order_hazardous_order_height_m_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mašinos tipas'),
        ),
    ]
