# Generated by Django 4.2.7 on 2025-10-29 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0011_change_vehicle_type_to_free_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Pavadinimas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Miestas/Lokacija',
                'verbose_name_plural': 'Miestai/Lokacijos',
                'db_table': 'cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OtherCostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, unique=True, verbose_name='Aprašymas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Išlaidų tipas',
                'verbose_name_plural': 'Išlaidų tipai',
                'db_table': 'other_cost_types',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Pavadinimas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mašinos tipas',
                'verbose_name_plural': 'Mašinos tipai',
                'db_table': 'vehicle_types',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='ordercarrier',
            options={'ordering': ['sequence_order', 'id'], 'verbose_name': 'Užsakymo vežėjas/Sandėlys', 'verbose_name_plural': 'Užsakymo vežėjai/Sandėliai'},
        ),
        migrations.AlterModelOptions(
            name='orderstatushistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Užsakymo statuso istorija', 'verbose_name_plural': 'Užsakymo statuso istorijos'},
        ),
        migrations.RemoveIndex(
            model_name='ordercarrier',
            name='order_carri_order_i_3d65cf_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderstatushistory',
            name='order_statu_order_i_0ca161_idx',
        ),
        migrations.AlterField(
            model_name='ordercarrier',
            name='status',
            field=models.CharField(choices=[('new', 'Naujas'), ('in_progress', 'Vykdomas'), ('completed', 'Baigtas'), ('cancelled', 'Atšauktas')], default='new', max_length=20, verbose_name='Būsena'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Pakeitė'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='new_status',
            field=models.CharField(max_length=30, verbose_name='Naujas statusas'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='old_status',
            field=models.CharField(max_length=30, verbose_name='Senas statusas'),
        ),
        migrations.AddIndex(
            model_name='ordercarrier',
            index=models.Index(fields=['order'], name='order_carri_order_i_385b91_idx'),
        ),
        migrations.AddIndex(
            model_name='ordercarrier',
            index=models.Index(fields=['partner'], name='order_carri_partner_0552ca_idx'),
        ),
        migrations.AddIndex(
            model_name='ordercarrier',
            index=models.Index(fields=['status'], name='order_carri_status_c15240_idx'),
        ),
    ]
