# Generated by Django 4.2.7 on 2025-10-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_ordernumbersequence_order_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercarrier',
            name='documents_status',
            field=models.CharField(choices=[('not_received', 'Negauta'), ('waiting', 'Laukiama'), ('received', 'Gauta')], default='not_received', max_length=20, verbose_name='Dokumentų statusas'),
        ),
        migrations.AddField(
            model_name='ordercarrier',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Apmokėjimo data'),
        ),
    ]
