# Generated by Django 4.2.7 on 2025-10-31 12:53

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_ordercarrier_documents_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.IntegerField(default=0, help_text='Nustato tvarką, kuria kroviniai yra naudojami', verbose_name='Eiliškumas')),
                ('description', models.CharField(blank=True, help_text='Trumpas krovinių aprašymas', max_length=500, verbose_name='Aprašymas')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Svoris (kg)')),
                ('ldm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='LDM')),
                ('length_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Ilgis (m)')),
                ('width_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Plotis (m)')),
                ('height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Aukštis (m)')),
                ('is_palletized', models.BooleanField(default=False, verbose_name='Paletemis')),
                ('is_stackable', models.BooleanField(default=False, verbose_name='Stabeliuojamas')),
                ('vehicle_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mašinos tipas')),
                ('requires_forklift', models.BooleanField(default=False, verbose_name='Reikalingas keltuvas')),
                ('requires_crane', models.BooleanField(default=False, verbose_name='Reikalingas kranas')),
                ('requires_special_equipment', models.BooleanField(default=False, verbose_name='Reikalinga speciali įranga')),
                ('fragile', models.BooleanField(default=False, verbose_name='Trapus')),
                ('hazardous', models.BooleanField(default=False, verbose_name='Pavojingas')),
                ('temperature_controlled', models.BooleanField(default=False, verbose_name='Temperatūros kontrolė')),
                ('requires_permit', models.BooleanField(default=False, verbose_name='Reikalingas leidimas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_items', to='orders.order', verbose_name='Užsakymas')),
            ],
            options={
                'verbose_name': 'Krovinio aprašymas',
                'verbose_name_plural': 'Krovinių aprašymai',
                'db_table': 'cargo_items',
                'ordering': ['sequence_order', 'id'],
                'indexes': [models.Index(fields=['order'], name='cargo_items_order_i_ab5bc5_idx'), models.Index(fields=['sequence_order'], name='cargo_items_sequenc_74d8f0_idx')],
            },
        ),
    ]
