# Generated by Django 4.2.7 on 2025-11-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_vat_rate_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='route_from_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Maršrutas iš - Adresas'),
        ),
        migrations.AddField(
            model_name='order',
            name='route_from_city',
            field=models.CharField(blank=True, max_length=255, verbose_name='Maršrutas iš - Miestas'),
        ),
        migrations.AddField(
            model_name='order',
            name='route_from_country',
            field=models.CharField(default='Lietuva', help_text='Privalomas laukas', max_length=100, verbose_name='Maršrutas iš - Šalis'),
        ),
        migrations.AddField(
            model_name='order',
            name='route_from_postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Maršrutas iš - Pašto kodas'),
        ),
        migrations.AddField(
            model_name='order',
            name='route_to_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Maršrutas į - Adresas'),
        ),
        migrations.AddField(
            model_name='order',
            name='route_to_city',
            field=models.CharField(blank=True, max_length=255, verbose_name='Maršrutas į - Miestas'),
        ),
        migrations.AddField(
            model_name='order',
            name='route_to_country',
            field=models.CharField(default='Lietuva', help_text='Privalomas laukas', max_length=100, verbose_name='Maršrutas į - Šalis'),
        ),
        migrations.AddField(
            model_name='order',
            name='route_to_postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Maršrutas į - Pašto kodas'),
        ),
        migrations.AlterField(
            model_name='order',
            name='route_from',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Maršrutas iš (sena)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='route_to',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Maršrutas į (sena)'),
        ),
    ]
