# Generated by Django 4.2.7 on 2025-11-01 20:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_add_address_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='my_price_net',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Mano kaina be PVM'),
        ),
    ]
