# Generated by Django 4.2.7 on 2025-11-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_remove_my_price_net_min_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercarrier',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Apmokėti iki'),
        ),
        migrations.AddField(
            model_name='ordercarrier',
            name='invoice_received_date',
            field=models.DateField(blank=True, null=True, verbose_name='Kada gauta sąskaita'),
        ),
        migrations.AddField(
            model_name='ordercarrier',
            name='payment_days',
            field=models.IntegerField(blank=True, help_text='Per kiek dienų nuo sąskaitos gavimo reikia apmokėti', null=True, verbose_name='Mokėjimo terminas (dienų)'),
        ),
    ]
