# Generated by Django 4.2.7 on 2025-11-03 13:36

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_contact_partner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0019_ordercarrier_due_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutocompleteSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('route_from_country', 'Maršrutas iš - Šalis'), ('route_from_postal_code', 'Maršrutas iš - Pašto kodas'), ('route_from_city', 'Maršrutas iš - Miestas'), ('route_from_address', 'Maršrutas iš - Adresas'), ('route_to_country', 'Maršrutas į - Šalis'), ('route_to_postal_code', 'Maršrutas į - Pašto kodas'), ('route_to_city', 'Maršrutas į - Miestas'), ('route_to_address', 'Maršrutas į - Adresas'), ('cargo_description', 'Krovinių aprašymas'), ('order_notes', 'Užsakymo pastabos'), ('carrier_notes', 'Vežėjo pastabos')], db_index=True, max_length=50, verbose_name='Lauko tipas')),
                ('value', models.CharField(max_length=500, verbose_name='Reikšmė')),
                ('usage_count', models.IntegerField(default=1, verbose_name='Naudojimų skaičius')),
                ('last_used_at', models.DateTimeField(auto_now=True, verbose_name='Paskutinį kartą naudota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
            ],
            options={
                'verbose_name': 'Autocomplete pasiūlymas',
                'verbose_name_plural': 'Autocomplete pasiūlymai',
                'db_table': 'autocomplete_suggestions',
                'ordering': ['-usage_count', '-last_used_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='ordernumbersequence',
            options={'ordering': ['-year'], 'verbose_name': 'Užsakymų numeracijos seka', 'verbose_name_plural': 'Užsakymų numeracijos sekos'},
        ),
        migrations.AlterModelOptions(
            name='orderstatushistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Užsakymo būsenos istorija', 'verbose_name_plural': 'Užsakymo būsenų istorijos'},
        ),
        migrations.RemoveIndex(
            model_name='cargoitem',
            name='cargo_items_sequenc_74d8f0_idx',
        ),
        migrations.RemoveField(
            model_name='cargoitem',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='order',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='other_costs',
        ),
        migrations.AlterField(
            model_name='cargoitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Aprašymas'),
        ),
        migrations.AlterField(
            model_name='cargoitem',
            name='height_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Aukštis (m)'),
        ),
        migrations.AlterField(
            model_name='cargoitem',
            name='ldm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='LDM'),
        ),
        migrations.AlterField(
            model_name='cargoitem',
            name='length_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Ilgis (m)'),
        ),
        migrations.AlterField(
            model_name='cargoitem',
            name='sequence_order',
            field=models.IntegerField(default=0, verbose_name='Eiliškumas'),
        ),
        migrations.AlterField(
            model_name='cargoitem',
            name='width_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Plotis (m)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_invoice_issued',
            field=models.BooleanField(default=False, verbose_name='Išrašyta kliento sąskaita'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_invoice_received',
            field=models.BooleanField(default=False, verbose_name='Gauta kliento sąskaita'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_price_net',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Kaina klientui (be PVM)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='height_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Aukštis (m)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_partial',
            field=models.BooleanField(default=False, verbose_name='Dalinis'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ldm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='LDM'),
        ),
        migrations.AlterField(
            model_name='order',
            name='length_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Ilgis (m)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='my_price_net',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Mano kaina (be PVM)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_net',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Kaina (be PVM)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='route_from',
            field=models.CharField(blank=True, max_length=500, verbose_name='Maršrutas iš'),
        ),
        migrations.AlterField(
            model_name='order',
            name='route_from_country',
            field=models.CharField(blank=True, max_length=255, verbose_name='Maršrutas iš - Šalis'),
        ),
        migrations.AlterField(
            model_name='order',
            name='route_to',
            field=models.CharField(blank=True, max_length=500, verbose_name='Maršrutas į'),
        ),
        migrations.AlterField(
            model_name='order',
            name='route_to_country',
            field=models.CharField(blank=True, max_length=255, verbose_name='Maršrutas į - Šalis'),
        ),
        migrations.AlterField(
            model_name='order',
            name='vat_rate_article',
            field=models.CharField(blank=True, max_length=50, verbose_name='PVM tarifo straipsnis'),
        ),
        migrations.AlterField(
            model_name='order',
            name='width_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Plotis (m)'),
        ),
        migrations.AlterField(
            model_name='ordercarrier',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_carriers', to='partners.partner', verbose_name='Partneris'),
        ),
        migrations.AlterField(
            model_name='ordercarrier',
            name='price_net',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Kaina (be PVM)'),
        ),
        migrations.AlterField(
            model_name='ordercarrier',
            name='route_from',
            field=models.CharField(blank=True, max_length=500, verbose_name='Maršrutas iš'),
        ),
        migrations.AlterField(
            model_name='ordercarrier',
            name='route_to',
            field=models.CharField(blank=True, max_length=500, verbose_name='Maršrutas į'),
        ),
        migrations.AlterField(
            model_name='ordercarrier',
            name='sequence_order',
            field=models.IntegerField(default=0, verbose_name='Eiliškumas'),
        ),
        migrations.AlterField(
            model_name='ordercarrier',
            name='status',
            field=models.CharField(choices=[('new', 'Naujas'), ('in_progress', 'Vykdomas'), ('completed', 'Baigtas'), ('cancelled', 'Atšauktas')], default='new', max_length=20, verbose_name='Statusas'),
        ),
        migrations.AlterField(
            model_name='ordernumbersequence',
            name='last_number',
            field=models.IntegerField(default=0, verbose_name='Paskutinis numeris'),
        ),
        migrations.AlterField(
            model_name='ordernumbersequence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atnaujinta'),
        ),
        migrations.AlterField(
            model_name='ordernumbersequence',
            name='year',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='Metai'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Pakeitė'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='new_status',
            field=models.CharField(choices=[('new', 'Naujas'), ('assigned', 'Priskirtas'), ('executing', 'Vykdomas'), ('waiting_for_docs', 'Laukiama Dokumentų'), ('finished', 'Baigtas (Sąskaitos Išrašymo Galima)'), ('canceled', 'Atšauktas')], max_length=30, verbose_name='Nauja būsena'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='old_status',
            field=models.CharField(blank=True, choices=[('new', 'Naujas'), ('assigned', 'Priskirtas'), ('executing', 'Vykdomas'), ('waiting_for_docs', 'Laukiama Dokumentų'), ('finished', 'Baigtas (Sąskaitos Išrašymo Galima)'), ('canceled', 'Atšauktas')], max_length=30, null=True, verbose_name='Sena būsena'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['order'], name='order_statu_order_i_8ab903_idx'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['created_at'], name='order_statu_created_0970b5_idx'),
        ),
        migrations.AddIndex(
            model_name='autocompletesuggestion',
            index=models.Index(fields=['field_type', 'value'], name='autocomplet_field_t_9dfb95_idx'),
        ),
        migrations.AddIndex(
            model_name='autocompletesuggestion',
            index=models.Index(fields=['field_type', '-usage_count', '-last_used_at'], name='autocomplet_field_t_9b9eee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='autocompletesuggestion',
            unique_together={('field_type', 'value')},
        ),
    ]
