# Generated by Django 4.2.7 on 2025-11-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_autocompletesuggestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='vat_rate_article',
            field=models.CharField(blank=True, max_length=500, verbose_name='PVM tarifo straipsnis'),
        ),
    ]
