# Generated by Django 4.2.7 on 2025-11-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_add_vehicle_type_to_autocomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='other_costs',
            field=models.JSONField(blank=True, default=list, help_text='JSON masyvas su aprašymais ir sumomis, pvz: [{"description": "Draudimas", "amount": 50.00}]', verbose_name='Kitos išlaidos'),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_route_to',
            field=models.CharField(blank=True, max_length=500, verbose_name='Gavėjas maršrute į'),
        ),
        migrations.AddField(
            model_name='order',
            name='sender_route_from',
            field=models.CharField(blank=True, max_length=500, verbose_name='Siuntėjas maršrute iš'),
        ),
        migrations.CreateModel(
            name='RouteContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('sender', 'Siuntėjas'), ('receiver', 'Gavėjas')], max_length=20, verbose_name='Tipas')),
                ('name', models.CharField(max_length=500, verbose_name='Siuntėjas/Gavėjas')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name='Šalis')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Pašto kodas')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='Miestas')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Adresas')),
                ('usage_count', models.IntegerField(default=1, verbose_name='Naudojimų skaičius')),
                ('last_used_at', models.DateTimeField(auto_now=True, verbose_name='Paskutinį kartą naudota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
            ],
            options={
                'verbose_name': 'Maršruto kontaktas',
                'verbose_name_plural': 'Maršruto kontaktai',
                'db_table': 'route_contacts',
                'ordering': ['-usage_count', '-last_used_at'],
                'indexes': [models.Index(fields=['contact_type', 'name'], name='route_conta_contact_b1d673_idx'), models.Index(fields=['contact_type', '-usage_count', '-last_used_at'], name='route_conta_contact_675822_idx')],
                'unique_together': {('contact_type', 'name', 'country', 'postal_code', 'city', 'address')},
            },
        ),
    ]
