# Generated by Django 4.2.7 on 2025-11-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_ordercarrier_expedition_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercarrier',
            name='expedition_number',
            field=models.CharField(
                max_length=32,
                blank=True,
                null=True,
                db_index=True,
                verbose_name='Ekspedicijos numeris',
            ),
        ),
    ]
