# Generated by Django 4.2.7 on 2025-11-10 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_remove_ordercarrier_order_carri_order_i_385b91_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCarrierDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('invoice', 'Sąskaita'), ('cmr', 'CMR'), ('other', 'Kiti dokumentai')], default='other', max_length=32, verbose_name='Dokumento tipas')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Suma (be PVM)')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Išrašymo data')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='Gavimo data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ekspedicijos dokumentas',
                'verbose_name_plural': 'Ekspedicijos dokumentai',
                'db_table': 'order_carrier_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='ordercarrier',
            name='order_carri_order_i_385b91_idx',
        ),
        migrations.RemoveIndex(
            model_name='ordercarrier',
            name='order_carri_partner_0552ca_idx',
        ),
        migrations.RemoveIndex(
            model_name='ordercarrier',
            name='order_carri_status_c15240_idx',
        ),
        migrations.AddIndex(
            model_name='ordercarrier',
            index=models.Index(fields=['expedition_number'], name='order_carri_expedit_8a5c0d_idx'),
        ),
        migrations.AddField(
            model_name='ordercarrierdocument',
            name='order_carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='orders.ordercarrier', verbose_name='Ekspedicija'),
        ),
    ]
