# Generated by Django 4.2.7 on 2025-11-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_order_type_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autocompletesuggestion',
            name='field_type',
            field=models.CharField(choices=[('route_from_country', 'Maršrutas iš - Šalis'), ('route_from_postal_code', 'Maršrutas iš - Pašto kodas'), ('route_from_city', 'Maršrutas iš - Miestas'), ('route_from_address', 'Maršrutas iš - Adresas'), ('route_to_country', 'Maršrutas į - Šalis'), ('route_to_postal_code', 'Maršrutas į - Pašto kodas'), ('route_to_city', 'Maršrutas į - Miestas'), ('route_to_address', 'Maršrutas į - Adresas'), ('cargo_description', 'Krovinių aprašymas'), ('order_notes', 'Užsakymo pastabos'), ('carrier_notes', 'Vežėjo pastabos'), ('vehicle_type', 'Mašinos tipas'), ('order_type', 'Užsakymo tipas')], db_index=True, max_length=50, verbose_name='Lauko tipas'),
        ),
    ]
