# Generated by Django 4.2.7 on 2025-11-15 09:17

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_alter_autocompletesuggestion_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercarrier',
            name='vat_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Jei nenurodytas, naudojamas užsakymo PVM tarifas', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='PVM tarifas (%)'),
        ),
        migrations.AddField(
            model_name='ordercarrier',
            name='vat_rate_article',
            field=models.CharField(blank=True, max_length=500, verbose_name='PVM tarifo straipsnis'),
        ),
    ]
