# Generated by Django 4.2.7 on 2025-11-21 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_order_other_costs_order_receiver_route_to_and_more'),
        ('orders', '0039_ordercarrier_payment_terms'),
    ]

    operations = [
    ]
