# Generated by Django 4.2.7 on 2025-11-21 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_alter_autocompletesuggestion_field_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoitem',
            name='package_count',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pakuočių skaičius'),
        ),
        migrations.AddField(
            model_name='cargoitem',
            name='pallet_count',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Paletių skaičius'),
        ),
        migrations.AddField(
            model_name='cargoitem',
            name='reference_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Referencinis numeris'),
        ),
        migrations.AddField(
            model_name='cargoitem',
            name='units',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Vienetai'),
        ),
        # OrderStatusHistory jau ištrintas - praleisti
        # migrations.DeleteModel(
        #     name='OrderStatusHistory',
        # ),
    ]
