# Generated by Django 4.2.7 on 2025-11-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0042_cargoitem_package_count_cargoitem_pallet_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoitem',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Pastabos'),
        ),
        # OrderStatusHistory jau ištrintas
        # migrations.DeleteModel(
        #     name='OrderStatusHistory',
        # ),
    ]
