# Generated by Django 4.2.7 on 2025-11-21 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_cargoitem_notes_delete_orderstatushistory'),
    ]

    operations = [
        # OrderStatusHistory jau ištrintas anksčiau
        # migrations.DeleteModel(
        #     name='OrderStatusHistory',
        # ),
    ]
