# Generated by Django 4.2.7 on 2025-11-25 11:57

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_partner_email_notify_manager_invoices'),
        ('orders', '0044_delete_orderstatushistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoItemNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_id', models.CharField(help_text='Unikalus krovinio identifikatorius užsakymo viduje (pvz., cargo_A, cargo_B)', max_length=50, verbose_name='Krovinio ID')),
                ('sequence_order', models.IntegerField(default=0, verbose_name='Eiliškumas')),
                ('reference_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Referencinis numeris')),
                ('description', models.TextField(blank=True, verbose_name='Aprašymas')),
                ('units', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Vienetai')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Svoris (kg)')),
                ('ldm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='LDM')),
                ('pallet_count', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Paletių skaičius')),
                ('package_count', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pakuočių skaičius')),
                ('length_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Ilgis (m)')),
                ('width_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Plotis (m)')),
                ('height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Aukštis (m)')),
                ('is_palletized', models.BooleanField(default=False, verbose_name='Paletemis')),
                ('is_stackable', models.BooleanField(default=False, verbose_name='Stabeliuojamas')),
                ('vehicle_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mašinos tipas')),
                ('requires_forklift', models.BooleanField(default=False, verbose_name='Reikalingas keltuvas')),
                ('requires_crane', models.BooleanField(default=False, verbose_name='Reikalingas kranas')),
                ('requires_special_equipment', models.BooleanField(default=False, verbose_name='Reikalinga speciali įranga')),
                ('fragile', models.BooleanField(default=False, verbose_name='Trapus')),
                ('hazardous', models.BooleanField(default=False, verbose_name='Pavojingas')),
                ('temperature_controlled', models.BooleanField(default=False, verbose_name='Temperatūros kontrolė')),
                ('requires_permit', models.BooleanField(default=False, verbose_name='Reikalingas leidimas')),
                ('notes', models.TextField(blank=True, verbose_name='Pastabos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Krovinys (naujas)',
                'verbose_name_plural': 'Kroviniai (nauji)',
                'db_table': 'cargo_items_new',
                'ordering': ['sequence_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CarrierAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expedition_number', models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='Ekspedicijos numeris')),
                ('price_net', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Kaina (be PVM)')),
                ('vat_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='PVM tarifas (%)')),
                ('status', models.CharField(choices=[('new', 'Naujas'), ('assigned', 'Priskirtas'), ('in_progress', 'Vykdomas'), ('completed', 'Baigtas'), ('cancelled', 'Atšauktas')], default='new', max_length=20, verbose_name='Statusas')),
                ('notes', models.TextField(blank=True, verbose_name='Pastabos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(limit_choices_to={'is_supplier': True}, on_delete=django.db.models.deletion.PROTECT, related_name='carrier_assignments', to='partners.partner', verbose_name='Vežėjas')),
            ],
            options={
                'verbose_name': 'Vežėjo priskyrimas',
                'verbose_name_plural': 'Vežėjų priskyrimai',
                'db_table': 'carrier_assignments',
                'ordering': ['start_stop__sequence_index'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(help_text='Unikalus taško identifikatorius užsakymo viduje (pvz., stop_1, stop_2)', max_length=50, verbose_name='Taško ID')),
                ('sequence_index', models.IntegerField(help_text='Maršruto taško eiliškumas (0, 1, 2, ...)', verbose_name='Eiliškumas')),
                ('stop_type', models.CharField(choices=[('pickup', 'Pasikrovimas'), ('delivery', 'Iškrovimas'), ('waypoint', 'Tarpinis taškas')], max_length=20, verbose_name='Taško tipas')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name='Šalis')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Pašto kodas')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='Miestas')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Adresas')),
                ('contact_name', models.CharField(blank=True, max_length=500, verbose_name='Kontaktinis asmuo/įmonė')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Telefono numeris')),
                ('contact_email', models.CharField(blank=True, max_length=255, verbose_name='El. paštas')),
                ('planned_date', models.DateTimeField(blank=True, null=True, verbose_name='Planuojama data')),
                ('actual_date', models.DateTimeField(blank=True, null=True, verbose_name='Faktinė data')),
                ('notes', models.TextField(blank=True, verbose_name='Pastabos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Maršruto taškas',
                'verbose_name_plural': 'Maršruto taškai',
                'db_table': 'route_stops',
                'ordering': ['sequence_index'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='route_type',
            field=models.CharField(choices=[('simple', 'Paprastas (1 → 1)'), ('multi_stop', 'Daugiataškis'), ('multi_cargo', 'Daugiakrovininis'), ('multi_carrier', 'Daugiavežėjinis')], default='simple', max_length=20, verbose_name='Maršruto tipas'),
        ),
        migrations.AddField(
            model_name='order',
            name='use_new_route_system',
            field=models.BooleanField(default=False, help_text='Jei True, naudojami RouteStop ir CargoItemNew modeliai', verbose_name='Naudoti naują maršruto sistemą'),
        ),
        migrations.DeleteModel(
            name='OrderStatusHistory',
        ),
        migrations.AddField(
            model_name='routestop',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='orders.order', verbose_name='Užsakymas'),
        ),
        migrations.AddField(
            model_name='carrierassignment',
            name='end_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carrier_assignments_end', to='orders.routestop', verbose_name='Pabaigos taškas'),
        ),
        migrations.AddField(
            model_name='carrierassignment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrier_assignments', to='orders.order', verbose_name='Užsakymas'),
        ),
        migrations.AddField(
            model_name='carrierassignment',
            name='start_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carrier_assignments_start', to='orders.routestop', verbose_name='Pradžios taškas'),
        ),
        migrations.AddField(
            model_name='cargoitemnew',
            name='load_at_stop',
            field=models.ForeignKey(help_text='Maršruto taškas, kur krovinys bus pakrautas', on_delete=django.db.models.deletion.PROTECT, related_name='pickup_cargo_items', to='orders.routestop', verbose_name='Pakrauti čia'),
        ),
        migrations.AddField(
            model_name='cargoitemnew',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_items_new', to='orders.order', verbose_name='Užsakymas'),
        ),
        migrations.AddField(
            model_name='cargoitemnew',
            name='unload_at_stop',
            field=models.ForeignKey(help_text='Maršruto taškas, kur krovinys bus iškrautas', on_delete=django.db.models.deletion.PROTECT, related_name='delivery_cargo_items', to='orders.routestop', verbose_name='Iškrauti čia'),
        ),
        migrations.AddIndex(
            model_name='routestop',
            index=models.Index(fields=['order', 'sequence_index'], name='route_stops_order_i_1e60d8_idx'),
        ),
        migrations.AddIndex(
            model_name='routestop',
            index=models.Index(fields=['order', 'stop_type'], name='route_stops_order_i_334006_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='routestop',
            unique_together={('order', 'stop_id')},
        ),
        migrations.AddIndex(
            model_name='carrierassignment',
            index=models.Index(fields=['order'], name='carrier_ass_order_i_971db4_idx'),
        ),
        migrations.AddIndex(
            model_name='carrierassignment',
            index=models.Index(fields=['carrier'], name='carrier_ass_carrier_7dae5a_idx'),
        ),
        migrations.AddIndex(
            model_name='carrierassignment',
            index=models.Index(fields=['expedition_number'], name='carrier_ass_expedit_6a0f0a_idx'),
        ),
        migrations.AddIndex(
            model_name='cargoitemnew',
            index=models.Index(fields=['order'], name='cargo_items_order_i_2a7e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='cargoitemnew',
            index=models.Index(fields=['load_at_stop'], name='cargo_items_load_at_bb4e46_idx'),
        ),
        migrations.AddIndex(
            model_name='cargoitemnew',
            index=models.Index(fields=['unload_at_stop'], name='cargo_items_unload__b9f233_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cargoitemnew',
            unique_together={('order', 'cargo_id')},
        ),
    ]
