# Generated by Django 4.2.7 on 2025-11-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0046_remove_carrierassignment_carrier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercarrier',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Gavėjas'),
        ),
        migrations.AddField(
            model_name='ordercarrier',
            name='sender_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Siuntėjas'),
        ),
    ]
