# Generated by Django 4.2.7 on 2025-11-28 10:43

from django.db import migrations, models


def merge_autocomplete_field_types(apps, schema_editor):
    """Sujungia route_from_* ir route_to_* į bendras kategorijas"""
    AutocompleteSuggestion = apps.get_model('orders', 'AutocompleteSuggestion')

    # Žemėlapiai senų į naujas reikšmes
    field_type_mapping = {
        'route_from_country': 'country',
        'route_to_country': 'country',
        'route_from_postal_code': 'postal_code',
        'route_to_postal_code': 'postal_code',
        'route_from_city': 'city',
        'route_to_city': 'city',
        'route_from_address': 'address',
        'route_to_address': 'address',
    }

    # Perkeliame duomenis
    for old_field_type, new_field_type in field_type_mapping.items():
        # Gauname visus įrašus su senu field_type
        old_suggestions = AutocompleteSuggestion.objects.filter(field_type=old_field_type)

        for old_suggestion in old_suggestions:
            # Tikriname ar naujas įrašas jau egzistuoja
            existing = AutocompleteSuggestion.objects.filter(
                field_type=new_field_type,
                value=old_suggestion.value
            ).first()

            if existing:
                # Jei egzistuoja, padidiname usage_count ir atnaujiname last_used_at
                existing.usage_count += old_suggestion.usage_count
                if old_suggestion.last_used_at > existing.last_used_at:
                    existing.last_used_at = old_suggestion.last_used_at
                existing.save()
                # Ištriname seną įrašą
                old_suggestion.delete()
            else:
                # Jei neegzistuoja, pakeičiame field_type
                old_suggestion.field_type = new_field_type
                old_suggestion.save()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0047_remove_carrierassignment_carrier_and_more'),
    ]

    operations = [
        # Pirmiau atliekame duomenų migraciją
        migrations.RunPython(merge_autocomplete_field_types),

        # Tada keičiame modelį
        migrations.AlterField(
            model_name='autocompletesuggestion',
            name='field_type',
            field=models.CharField(
                choices=[
                    ('country', 'Šalis'),
                    ('postal_code', 'Pašto kodas'),
                    ('city', 'Miestas'),
                    ('address', 'Adresas'),
                    ('cargo_description', 'Krovinių aprašymas'),
                    ('order_notes', 'Užsakymo pastabos'),
                    ('carrier_notes', 'Vežėjo pastabos'),
                    ('vehicle_type', 'Mašinos tipas'),
                    ('order_type', 'Užsakymo tipas')
                ],
                db_index=True,
                max_length=50,
                verbose_name='Lauko tipas'
            ),
        ),
    ]
