# Generated by Django 4.2.7 on 2025-11-28 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0048_merge_autocomplete_field_types'),
    ]

    operations = [
        # Only remove the OrderCarrier fields that exist in the database
        migrations.RemoveField(
            model_name='ordercarrier',
            name='receiver_name',
        ),
        migrations.RemoveField(
            model_name='ordercarrier',
            name='route_from_address',
        ),
        migrations.RemoveField(
            model_name='ordercarrier',
            name='route_from_city',
        ),
        migrations.RemoveField(
            model_name='ordercarrier',
            name='route_from_country',
        ),
        migrations.RemoveField(
            model_name='ordercarrier',
            name='route_from_postal_code',
        ),
        migrations.RemoveField(
            model_name='ordercarrier',
            name='route_to_address',
        ),
        migrations.RemoveField(
            model_name='ordercarrier',
            name='route_to_city',
        ),
        migrations.RemoveField(
            model_name='ordercarrier',
            name='route_to_country',
        ),
        migrations.RemoveField(
            model_name='ordercarrier',
            name='route_to_postal_code',
        ),
        migrations.RemoveField(
            model_name='ordercarrier',
            name='sender_name',
        ),
    ]
