# Generated by Django 4.2.7 on 2025-11-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0049_remove_ordercarrier_route_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercarrier',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Gavėjo pavadinimas'),
        ),
        migrations.AddField(
            model_name='ordercarrier',
            name='sender_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Siuntėjo pavadinimas'),
        ),
    ]
