# Generated by Django 4.2.7 on 2026-01-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0051_add_route_detail_fields_to_ordercarrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='loading_date_from',
            field=models.DateField(blank=True, null=True, verbose_name='Pakrovimas nuo'),
        ),
        migrations.AddField(
            model_name='order',
            name='loading_date_to',
            field=models.DateField(blank=True, null=True, verbose_name='Pakrovimas iki'),
        ),
        migrations.AddField(
            model_name='order',
            name='unloading_date_from',
            field=models.DateField(blank=True, null=True, verbose_name='Iškrovimas nuo'),
        ),
        migrations.AddField(
            model_name='order',
            name='unloading_date_to',
            field=models.DateField(blank=True, null=True, verbose_name='Iškrovimas iki'),
        ),
    ]
