# Generated by Django 4.2.7 on 2026-01-05 11:40

from django.db import migrations


def migrate_existing_dates_forward(apps, schema_editor):
    """Perkelti senas datas į naujus intervalų laukus"""
    Order = apps.get_model('orders', 'Order')

    # Atnaujinti užsakymus, kurie turi senas datas bet neturi naujų
    orders_to_update = Order.objects.filter(
        loading_date__isnull=False,
        loading_date_from__isnull=True
    ) | Order.objects.filter(
        unloading_date__isnull=False,
        unloading_date_from__isnull=True
    )

    updated_count = 0
    for order in orders_to_update:
        needs_update = False

        # Jei turi loading_date bet neturi loading_date_from - nukopijuoti
        if order.loading_date and not order.loading_date_from:
            order.loading_date_from = order.loading_date.date()  # Konvertuoti į datą
            needs_update = True

        # Jei turi unloading_date bet neturi unloading_date_from - nukopijuoti
        if order.unloading_date and not order.unloading_date_from:
            order.unloading_date_from = order.unloading_date.date()  # Konvertuoti į datą
            needs_update = True

        if needs_update:
            order.save()
            updated_count += 1

    print(f"Migrated dates for {updated_count} orders")


def migrate_existing_dates_reverse(apps, schema_editor):
    """Atgalinė migracija - nekeičiam, nes duomenys išsaugoti"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0052_add_date_intervals_only'),
    ]

    operations = [
        migrations.RunPython(
            migrate_existing_dates_forward,
            migrate_existing_dates_reverse
        ),
    ]
