# Generated by Django 4.2.7 on 2026-01-06 13:26

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0054_add_carrier_date_intervals_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrierassignment',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='carrierassignment',
            name='end_stop',
        ),
        migrations.RemoveField(
            model_name='carrierassignment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='carrierassignment',
            name='start_stop',
        ),
        migrations.AlterUniqueTogether(
            name='routestop',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='routestop',
            name='order',
        ),
        migrations.RemoveField(
            model_name='expeditionnumbersequence',
            name='last_number',
        ),
        migrations.AddField(
            model_name='expeditionnumbersequence',
            name='last_carrier_number',
            field=models.IntegerField(default=0, verbose_name='Paskutinis vežėjo ekspedicijos numeris'),
        ),
        migrations.AddField(
            model_name='expeditionnumbersequence',
            name='last_cost_number',
            field=models.IntegerField(default=0, verbose_name='Paskutinis išlaidų ekspedicijos numeris'),
        ),
        migrations.AddField(
            model_name='expeditionnumbersequence',
            name='last_warehouse_number',
            field=models.IntegerField(default=0, verbose_name='Paskutinis sandėlio ekspedicijos numeris'),
        ),
        migrations.AddField(
            model_name='ordercarrier',
            name='custom_loading_date_from',
            field=models.DateField(blank=True, null=True, verbose_name='Custom pakrovimas nuo'),
        ),
        migrations.AddField(
            model_name='ordercarrier',
            name='custom_loading_date_to',
            field=models.DateField(blank=True, null=True, verbose_name='Custom pakrovimas iki'),
        ),
        migrations.AddField(
            model_name='ordercarrier',
            name='custom_route_from',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Custom maršrutas iš'),
        ),
        migrations.AddField(
            model_name='ordercarrier',
            name='custom_route_from_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Custom maršrutas iš - Adresas'),
        ),
        migrations.AddField(
            model_name='ordercarrier',
            name='custom_route_from_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Custom maršrutas iš - Miestas'),
        ),
        migrations.AddField(
            model_name='ordercarrier',
            name='custom_route_from_country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Custom maršrutas iš - Šalis'),
        ),
        migrations.AddField(
            model_name='ordercarrier',
            name='custom_route_to',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Custom maršrutas į'),
        ),
        migrations.AddField(
            model_name='ordercarrier',
            name='custom_route_to_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Custom maršrutas į - Adresas'),
        ),
        migrations.AddField(
            model_name='ordercarrier',
            name='custom_route_to_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Custom maršrutas į - Miestas'),
        ),
        migrations.AddField(
            model_name='ordercarrier',
            name='custom_route_to_country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Custom maršrutas į - Šalis'),
        ),
        migrations.AddField(
            model_name='ordercarrier',
            name='custom_unloading_date_from',
            field=models.DateField(blank=True, null=True, verbose_name='Custom iškrovimas nuo'),
        ),
        migrations.AddField(
            model_name='ordercarrier',
            name='custom_unloading_date_to',
            field=models.DateField(blank=True, null=True, verbose_name='Custom iškrovimas iki'),
        ),
        migrations.AddField(
            model_name='ordercarrier',
            name='has_custom_dates',
            field=models.BooleanField(default=False, verbose_name='Turi custom datas'),
        ),
        migrations.AddField(
            model_name='ordercarrier',
            name='has_custom_route',
            field=models.BooleanField(default=False, verbose_name='Turi custom maršrutą'),
        ),
        # Removed AlterField for ordercost - model doesn't exist yet at this migration point
        migrations.DeleteModel(
            name='CargoItemNew',
        ),
        migrations.DeleteModel(
            name='CarrierAssignment',
        ),
        migrations.DeleteModel(
            name='RouteStop',
        ),
    ]
