# Generated by Django 4.2.7 on 2026-01-07 10:25

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_add_sender_classification'),
        ('orders', '0056_remove_carrierassignment_carrier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordercarrierdocument',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vežėjo dokumentas', 'verbose_name_plural': 'Vežėjo dokumentai'},
        ),
        migrations.AddField(
            model_name='cargoitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='OrderCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expedition_number', models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='Išlaidų ekspedicijos numeris')),
                ('cost_type', models.CharField(choices=[('insurance', 'Draudimas'), ('customs', 'Muitinės paslaugos'), ('storage', 'Saugojimas/Sandėliavimas'), ('fuel', 'Kuras/Degalinės'), ('toll', 'Kelių mokestis'), ('repair', 'Remontas'), ('other', 'Kita')], default='other', max_length=20, verbose_name='Išlaidų tipas')),
                ('status', models.CharField(choices=[('new', 'Nauja'), ('in_progress', 'Vykdoma'), ('completed', 'Užbaigta'), ('cancelled', 'Atšaukta')], default='new', max_length=20, verbose_name='Statusas')),
                ('description', models.TextField(verbose_name='Aprašymas')),
                ('amount_net', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Suma (be PVM)')),
                ('vat_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Jei nenurodytas, naudojamas užsakymo PVM tarifas', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='PVM tarifas (%)')),
                ('invoice_issued', models.BooleanField(default=False, verbose_name='Sąskaita išrašyta')),
                ('invoice_received', models.BooleanField(default=False, verbose_name='Sąskaita gauta')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Sąskaitos numeris')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Sąskaitos data')),
                ('payment_status', models.CharField(choices=[('not_paid', 'Neapmokėtas'), ('partially_paid', 'Dalinai apmokėtas'), ('paid', 'Apmokėtas'), ('overdue', 'Pavėluotas')], default='not_paid', max_length=20, verbose_name='Mokėjimo statusas')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Mokėjimo data')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Terminas')),
                ('payment_terms', models.TextField(blank=True, verbose_name='Mokėjimo sąlygos')),
                ('sequence_order', models.IntegerField(default=0, verbose_name='Eiliškumas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='orders.order', verbose_name='Užsakymas')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_costs', to='partners.partner', verbose_name='Tiekėjas')),
            ],
            options={
                'verbose_name': 'Užsakymo išlaida',
                'verbose_name_plural': 'Užsakymo išlaidos',
                'db_table': 'order_costs',
                'ordering': ['sequence_order'],
            },
        ),
    ]
