# Generated by Django 4.2.7 on 2026-01-10 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_order_other_costs_order_receiver_route_to_and_more'),
        ('orders', '0057_add_ordercost_model'),
    ]

    operations = [
    ]
