# Generated by Django 4.2.7 on 2026-01-10 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_add_vehicle_type_to_autocomplete'),
        ('orders', '0058_merge_20260110_1316'),
    ]

    operations = [
    ]
