# Generated by Django 4.2.7 on 2026-01-10 18:30

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_merge_20251216_1858'),
        ('orders', '0059_merge_20260110_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordercarrierdocument',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ekspedicijos dokumentas', 'verbose_name_plural': 'Ekspedicijos dokumentai'},
        ),
        migrations.AlterModelOptions(
            name='ordercost',
            options={'ordering': ['sequence_order', 'id'], 'verbose_name': 'Papildoma išlaida', 'verbose_name_plural': 'Papildomos išlaidos'},
        ),
        migrations.RemoveField(
            model_name='cargoitem',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='ordercost',
            name='amount_with_vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Suma su PVM'),
        ),
        migrations.AddField(
            model_name='ordercost',
            name='vat_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='PVM suma'),
        ),
        migrations.AlterField(
            model_name='ordercost',
            name='amount_net',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Suma (be PVM)'),
        ),
        migrations.AlterField(
            model_name='ordercost',
            name='description',
            field=models.TextField(blank=True, verbose_name='Aprašymas'),
        ),
        migrations.AlterField(
            model_name='ordercost',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Apmokėti iki'),
        ),
        migrations.AlterField(
            model_name='ordercost',
            name='expedition_number',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='Išlaidų numeris'),
        ),
        migrations.AlterField(
            model_name='ordercost',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Sąskaitos numeris'),
        ),
        migrations.AlterField(
            model_name='ordercost',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_costs', to='partners.partner', verbose_name='Tiekėjas/Partneris'),
        ),
        migrations.AlterField(
            model_name='ordercost',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Apmokėjimo data'),
        ),
        migrations.AlterField(
            model_name='ordercost',
            name='payment_status',
            field=models.CharField(choices=[('not_paid', 'Neapmokėta'), ('partially_paid', 'Dalinai apmokėta'), ('paid', 'Apmokėta')], default='not_paid', max_length=20, verbose_name='Mokėjimo būsena'),
        ),
        migrations.AlterField(
            model_name='ordercost',
            name='status',
            field=models.CharField(choices=[('new', 'Nauja'), ('in_progress', 'Vykdoma'), ('completed', 'Užbaigta'), ('cancelled', 'Atšaukta')], default='new', max_length=20, verbose_name='Būsena'),
        ),
        migrations.AddIndex(
            model_name='ordercost',
            index=models.Index(fields=['order', 'cost_type'], name='order_costs_order_i_c5ae63_idx'),
        ),
        migrations.AddIndex(
            model_name='ordercost',
            index=models.Index(fields=['expedition_number'], name='order_costs_expedit_61f807_idx'),
        ),
        migrations.AddIndex(
            model_name='ordercost',
            index=models.Index(fields=['status', 'due_date'], name='order_costs_status_ba5faa_idx'),
        ),
    ]
