# Generated by Django 4.2.7 on 2026-01-11 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0060_alter_ordercarrierdocument_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_type', models.CharField(choices=[('loading', 'Pakrovimas'), ('unloading', 'Iškrovimas')], max_length=20, verbose_name='Sustojimo tipas')),
                ('sequence_order', models.IntegerField(default=0, verbose_name='Eiliškumas')),
                ('name', models.CharField(blank=True, max_length=500, verbose_name='Siuntėjas/Gavėjas')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name='Šalis')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Pašto kodas')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='Miestas')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Adresas')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Data nuo')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Data iki')),
                ('notes', models.TextField(blank=True, verbose_name='Pastabos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='orders.order', verbose_name='Užsakymas')),
            ],
            options={
                'verbose_name': 'Maršruto sustojimas',
                'verbose_name_plural': 'Maršruto sustojimai',
                'db_table': 'order_route_stops',
                'ordering': ['sequence_order', 'id'],
            },
        ),
    ]
