# Generated by Django 4.2.7 on 2026-01-11 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0061_routestop'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoitem',
            name='loading_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loading_cargo_items', to='orders.routestop', verbose_name='Pakrovimo sustojimas'),
        ),
        migrations.AddField(
            model_name='cargoitem',
            name='unloading_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unloading_cargo_items', to='orders.routestop', verbose_name='Iškrovimo sustojimas'),
        ),
    ]
