# Generated by Django 4.2.7 on 2026-01-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0062_cargoitem_loading_stop_cargoitem_unloading_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_order_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Užsakovo užsakymo numeris'),
        ),
    ]
