# Generated by Django 4.2.7 on 2026-01-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0063_order_client_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='loading_date_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pakrovimas nuo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='loading_date_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pakrovimas iki'),
        ),
        migrations.AlterField(
            model_name='order',
            name='unloading_date_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Iškrovimas nuo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='unloading_date_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Iškrovimas iki'),
        ),
        migrations.AlterField(
            model_name='ordercarrier',
            name='loading_date_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pakrovimas nuo'),
        ),
        migrations.AlterField(
            model_name='ordercarrier',
            name='loading_date_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pakrovimas iki'),
        ),
        migrations.AlterField(
            model_name='ordercarrier',
            name='unloading_date_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Iškrovimas nuo'),
        ),
        migrations.AlterField(
            model_name='ordercarrier',
            name='unloading_date_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Iškrovimas iki'),
        ),
    ]
