# Generated by Django 4.2.7 on 2026-01-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0064_change_date_intervals_to_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercarrier',
            name='custom_loading_date_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Custom pakrovimas nuo'),
        ),
        migrations.AlterField(
            model_name='ordercarrier',
            name='custom_loading_date_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Custom pakrovimas iki'),
        ),
        migrations.AlterField(
            model_name='ordercarrier',
            name='custom_unloading_date_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Custom iškrovimas nuo'),
        ),
        migrations.AlterField(
            model_name='ordercarrier',
            name='custom_unloading_date_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Custom iškrovimas iki'),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='date_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data nuo'),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='date_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data iki'),
        ),
    ]
