# Generated by Django 4.2.7 on 2026-01-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0065_change_routestop_dates_to_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Naujas'), ('assigned', 'Priskirtas'), ('executing', 'Vykdomas'), ('waiting_for_docs', 'Laukiama Dokumentų'), ('waiting_for_payment', 'Laukiama Apmokėjimo'), ('finished', 'Baigtas'), ('closed', 'Uždarytas'), ('canceled', 'Atšauktas')], db_index=True, default='new', max_length=30, verbose_name='Būsena'),
        ),
    ]
