# Generated by Django 4.2.7 on 2025-11-08 14:24

import apps.mail.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(help_text='Unikalus IMAP laiško identifikatorius (per aplanką).', max_length=128, unique=True, verbose_name='IMAP UID')),
                ('message_id', models.CharField(blank=True, help_text='Laiško Message-ID antraštė, jei yra.', max_length=255, verbose_name='Message-ID')),
                ('subject', models.CharField(blank=True, max_length=512, verbose_name='Tema')),
                ('sender', models.CharField(max_length=512, verbose_name='Siuntėjas')),
                ('recipients', models.TextField(blank=True, verbose_name='Gavėjai (To)')),
                ('cc', models.TextField(blank=True, verbose_name='Kopija (CC)')),
                ('bcc', models.TextField(blank=True, verbose_name='Nematomos kopijos (BCC)')),
                ('date', models.DateTimeField(verbose_name='Laiško data')),
                ('folder', models.CharField(default='INBOX', max_length=255, verbose_name='Aplankas')),
                ('status', models.CharField(choices=[('new', 'Naujas'), ('linked', 'Susietas'), ('ignored', 'Ignoruotas'), ('task', 'Užduotis')], default='new', max_length=32, verbose_name='Būsena')),
                ('flags', models.CharField(blank=True, max_length=255, verbose_name='IMAP vėliavėlės')),
                ('snippet', models.TextField(blank=True, verbose_name='Trumpas turinio fragmentas')),
                ('body_plain', models.TextField(blank=True, verbose_name='Turinys (paprastas tekstas)')),
                ('body_html', models.TextField(blank=True, verbose_name='Turinys (HTML)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Saugomos papildomos IMAP antraštės ar pagalbiniai duomenys.', verbose_name='Papildoma informacija')),
                ('related_order_id', models.IntegerField(blank=True, null=True, verbose_name='Susietas užsakymo ID')),
                ('related_partner_id', models.IntegerField(blank=True, null=True, verbose_name='Susietas partnerio ID')),
                ('assigned_to_id', models.IntegerField(blank=True, help_text='Jei reikia, priskiriame laišką konkretų vartotojui TMS sistemoje.', null=True, verbose_name='Priskirta vartotojui (ID)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atnaujinta')),
            ],
            options={
                'verbose_name': 'Laiškas',
                'verbose_name_plural': 'Laiškai',
                'db_table': 'mail_messages',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MailSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(default='INBOX', max_length=255, verbose_name='Aplankas')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Paskutinė sinchronizacija')),
                ('last_uid', models.CharField(blank=True, max_length=128, verbose_name='Paskutinis sinchronizuotas UID')),
                ('status', models.CharField(blank=True, max_length=32, verbose_name='Būsena')),
                ('message', models.TextField(blank=True, verbose_name='Pastabos / klaidos')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Papildoma informacija')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atnaujinta')),
            ],
            options={
                'verbose_name': 'Sinchronizacijos būsena',
                'verbose_name_plural': 'Sinchronizacijos būsenos',
                'db_table': 'mail_sync_state',
            },
        ),
        migrations.CreateModel(
            name='MailTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Žyma')),
                ('color', models.CharField(default='#6b7280', max_length=7, verbose_name='Spalva (HEX)')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Aprašymas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
            ],
            options={
                'verbose_name': 'Laiško žyma',
                'verbose_name_plural': 'Laiško žymos',
                'db_table': 'mail_tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Failo pavadinimas')),
                ('content_type', models.CharField(blank=True, max_length=128, verbose_name='Turinio tipas')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='Dydis (baitais)')),
                ('file', models.FileField(upload_to=apps.mail.models.attachment_upload_path, verbose_name='Failas')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Papildoma informacija')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
                ('mail_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mail.mailmessage', verbose_name='Laiškas')),
            ],
            options={
                'verbose_name': 'Laiško priedas',
                'verbose_name_plural': 'Laiško priedai',
                'db_table': 'mail_attachments',
            },
        ),
        migrations.CreateModel(
            name='MailMessageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Pridėta')),
                ('mail_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_tags', to='mail.mailmessage', verbose_name='Laiškas')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_messages', to='mail.mailtag', verbose_name='Žyma')),
            ],
            options={
                'verbose_name': 'Žymos ir laiško ryšys',
                'verbose_name_plural': 'Žymos ir laiško ryšiai',
                'db_table': 'mail_message_tags',
                'unique_together': {('mail_message', 'tag')},
            },
        ),
    ]
