# Generated by Django 4.2.7 on 2025-11-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailmessage',
            name='status',
            field=models.CharField(choices=[('new', 'Naujas'), ('linked', 'Skaitytas'), ('ignored', 'Ignoruotas'), ('task', 'Užduotis')], default='new', max_length=32, verbose_name='Būsena'),
        ),
    ]
