# Generated by Django 4.2.7 on 2025-11-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_emaillog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emaillog',
            new_name='email_logs_email_t_6d62ae_idx',
            old_name='email_logs_email_t_created_idx',
        ),
        migrations.RenameIndex(
            model_name='emaillog',
            new_name='email_logs_related_28d13e_idx',
            old_name='email_logs_related_order_idx',
        ),
        migrations.RenameIndex(
            model_name='emaillog',
            new_name='email_logs_related_c45eb6_idx',
            old_name='email_logs_related_invoice_idx',
        ),
        migrations.RenameIndex(
            model_name='emaillog',
            new_name='email_logs_status_012124_idx',
            old_name='email_logs_status_created_idx',
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(choices=[('reminder', 'Priminimas'), ('order', 'Užsakymas'), ('invoice', 'Sąskaita'), ('expedition', 'Ekspedicija'), ('manager_notification', 'Pranešimas vadybininkui'), ('custom', 'Kitas')], max_length=32, verbose_name='Tipas'),
        ),
    ]
