# Generated by Django 4.2.7 on 2025-11-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_add_matched_relations'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mailmessage',
            index=models.Index(fields=['status'], name='mail_messages_status_idx'),
        ),
        migrations.AddIndex(
            model_name='mailmessage',
            index=models.Index(fields=['folder'], name='mail_messages_folder_idx'),
        ),
        migrations.AddIndex(
            model_name='mailmessage',
            index=models.Index(fields=['-date'], name='mail_messages_date_idx'),
        ),
        migrations.AddIndex(
            model_name='mailmessage',
            index=models.Index(fields=['status', '-date'], name='mail_messages_status_date_idx'),
        ),
    ]
