# Generated by Django 4.2.7 on 2025-11-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_add_mail_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailmessage',
            name='is_promotional',
            field=models.BooleanField(db_index=True, default=False, help_text='Automatiškai nustatomas, jei laiškas atpažįstamas kaip reklaminis.', verbose_name='Reklaminis laiškas'),
        ),
        migrations.AddIndex(
            model_name='mailmessage',
            index=models.Index(fields=['is_promotional'], name='mail_msg_promo_idx'),
        ),
    ]
