# Generated by Django 4.2.7 on 2025-12-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0007_add_is_promotional_field'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mailmessage',
            index=models.Index(fields=['assigned_to_id'], name='mail_messages_assigned_idx'),
        ),
        migrations.AddIndex(
            model_name='mailmessage',
            index=models.Index(fields=['related_order_id'], name='mail_msg_rel_order_idx'),
        ),
    ]
