# Generated by Django 4.2.7 on 2025-12-04 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail', '0009_add_ocr_results_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('invoice', 'Sąskaita'), ('cmr', 'CMR važtaraštis'), ('tir', 'TIR dokumentas'), ('contract', 'Sutartis'), ('other', 'Kita')], max_length=20, verbose_name='Dokumento tipas')),
                ('field_mappings', models.JSONField(blank=True, default=dict, help_text='JSON objektas su laukų pavadinimais ir jų pozicijomis dokumente', verbose_name='Laukų pozicijos')),
                ('template_name', models.CharField(blank=True, help_text='Žmogui suprantamas šablono pavadinimas', max_length=200, verbose_name='Šablono pavadinimas')),
                ('confidence_score', models.FloatField(default=0.0, help_text='Kaip gerai šis šablonas atpažįsta dokumentus (0-1)', verbose_name='Pasitikėjimo lygis')),
                ('is_active', models.BooleanField(default=True, help_text='Ar šis šablonas naudojamas atpažinimui', verbose_name='Aktyvus')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atnaujinta')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to='mail.mailattachment', verbose_name='Priedas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Sukūrė')),
            ],
            options={
                'verbose_name': 'Dokumento šablonas',
                'verbose_name_plural': 'Dokumento šablonai',
                'db_table': 'document_templates',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['document_type', 'is_active'], name='document_te_documen_de5f57_idx'), models.Index(fields=['attachment'], name='document_te_attachm_4340a3_idx')],
            },
        ),
    ]
