# Generated by Django 4.2.7 on 2025-12-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0010_add_document_template_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailmessage',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False, help_text='Ar šis laiškas yra prisegtas svarbių laiškų sąraše.', verbose_name='Prisegtas laiškas'),
        ),
    ]
