# Generated by Django 4.2.7 on 2025-12-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0011_add_is_pinned_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailmessage',
            name='sender_safety_status',
            field=models.CharField(choices=[('safe', 'Saugus'), ('medium_risk', 'Vidutinė rizika'), ('high_risk', 'Aukšta rizika')], db_index=True, default='high_risk', help_text='Email saugumo lygis pagal mūsų kontaktų bazę.', max_length=20, verbose_name='Siuntėjo saugumo statusas'),
        ),
    ]
