# Generated by Django 4.2.7 on 2025-12-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0012_add_sender_safety_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailmessage',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, help_text='Ar šis laiškas buvo atidarytas ir perskaitytas.', verbose_name='Perskaitytas laiškas'),
        ),
    ]
