# Generated by Django 4.2.7 on 2025-12-16 08:59

import re
from email.utils import getaddresses

from django.db import migrations, models


def extract_email(sender: str) -> str:
    if not sender:
        return ''
    try:
        addresses = getaddresses([sender])
        if addresses:
            email_addr = addresses[0][1]
            if email_addr:
                return email_addr.strip().lower()
    except Exception:
        pass
    email_pattern = r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'
    match = re.search(email_pattern, sender)
    if match:
        return match.group(0).strip().lower()
    return ''


def populate_sender_email(apps, schema_editor):
    MailMessage = apps.get_model('mail', 'MailMessage')
    for message in MailMessage.objects.all():
        sender_value = extract_email(message.sender or '')
        if sender_value:
            MailMessage.objects.filter(pk=message.pk).update(sender_email=sender_value)


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0007_add_is_promotional_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True, verbose_name='El. pašto adresas')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Vardas / Įmonė')),
                ('is_trusted', models.BooleanField(default=False, verbose_name='Patikimas siuntėjas')),
                ('is_advertising', models.BooleanField(default=False, verbose_name='Reklaminis siuntėjas')),
                ('notes', models.TextField(blank=True, verbose_name='Pastabos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurtas')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atnaujintas')),
            ],
            options={
                'verbose_name': 'Siuntėjas',
                'verbose_name_plural': 'Siuntėjai',
                'ordering': ['email'],
            },
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='sender_email',
            field=models.CharField(blank=True, db_index=True, help_text='Automatiškai užpildoma iš siuntėjo lauko', max_length=255, verbose_name='Siuntėjo el. paštas (normalizuotas)'),
        ),
        migrations.RunPython(populate_sender_email, reverse_code=migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='mailmessage',
            index=models.Index(fields=['sender_email'], name='mail_messages_sender_email_idx'),
        ),
    ]
