# Generated by Django 4.2.7 on 2025-12-16 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0013_add_is_read_field'),
        ('mail', '0014_mailsender_mailmessage_sender_email_and_more'),
    ]

    operations = [
    ]
