# Generated by Django 4.2.7 on 2025-12-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0014_mailsender_mailmessage_sender_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailattachment',
            name='ocr_error',
            field=models.TextField(blank=True, null=True, verbose_name='OCR klaida'),
        ),
        migrations.AddField(
            model_name='mailattachment',
            name='ocr_processed',
            field=models.BooleanField(default=False, verbose_name='OCR atlikta'),
        ),
        migrations.AddField(
            model_name='mailattachment',
            name='ocr_processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OCR atlikta'),
        ),
        migrations.AddField(
            model_name='mailattachment',
            name='ocr_text',
            field=models.TextField(blank=True, null=True, verbose_name='OCR tekstas'),
        ),
    ]
