# Generated by Django 4.2.7 on 2025-12-24 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0015_add_ocr_fields'),
        ('mail', '0015_merge_20251216_1858'),
    ]

    operations = [
    ]
