# Generated by Django 4.2.7 on 2025-12-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0015_add_ocr_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailmessage',
            name='manually_assigned',
            field=models.BooleanField(db_index=True, default=False, help_text='True jei laiškas buvo priskirtas prie užsakymo rankiniu būdu (apsauga nuo OCR pakeitimų)', verbose_name='Rankiniu būdu priskirta'),
        ),
    ]
