# Generated by Django 4.2.7 on 2026-01-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0016_add_manually_assigned_field'),
        ('mail', '0016_merge_0015_add_ocr_fields_0015_merge_20251216_1858'),
    ]

    operations = [
    ]
