# Generated by Django 4.2.7 on 2026-01-10 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0017_merge_20260102_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttemplate',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='documenttemplate',
            name='created_by',
        ),
        migrations.RemoveIndex(
            model_name='mailmessage',
            name='mail_messages_assigned_idx',
        ),
        migrations.RemoveIndex(
            model_name='mailmessage',
            name='mail_msg_rel_order_idx',
        ),
        migrations.RemoveField(
            model_name='mailmessage',
            name='is_pinned',
        ),
        migrations.RemoveField(
            model_name='mailmessage',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='mailmessage',
            name='ocr_results',
        ),
        migrations.RemoveField(
            model_name='mailmessage',
            name='sender_safety_status',
        ),
        migrations.DeleteModel(
            name='DocumentTemplate',
        ),
    ]
