# Generated by Django 4.2.7 on 2026-01-15 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0021_merge_20260110_1316'),
        ('mail', '0018_remove_documenttemplate_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailattachment',
            name='related_purchase_invoice',
            field=models.ForeignKey(blank=True, help_text='Jei priedas buvo naudotas sukurti purchase invoice, čia saugomas ryšys', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_attachment', to='invoices.purchaseinvoice', verbose_name='Susijusi gauta sąskaita'),
        ),
    ]
