# Generated by Django 4.2.7 on 2025-12-05 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Domenas, kurio laiškai bus slepiami (pvz.: gmail.com, yahoo.com)', max_length=255, unique=True, verbose_name='Domenas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurtas')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atnaujintas')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sukūrė')),
            ],
            options={
                'verbose_name': 'Užblokuotas domenas',
                'verbose_name_plural': 'Užblokuoti domenai',
                'ordering': ['domain'],
            },
        ),
    ]
