# Generated by Django 4.2.7 on 2025-12-05 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blocked_domains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Siuntėjo el. pašto adresas, kuris nėra laikomas reklaminiu', max_length=254, unique=True, verbose_name='El. pašto adresas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sukurtas')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atnaujintas')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sukūrė')),
            ],
            options={
                'verbose_name': 'Patikimas siuntėjas',
                'verbose_name_plural': 'Patikimi siuntėjai',
                'ordering': ['email'],
            },
        ),
    ]
