# Generated by Django 4.2.7 on 2025-12-12 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blocked_domains', '0002_trustedsender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockeddomain',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sukūrė'),
        ),
        migrations.AlterField(
            model_name='trustedsender',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sukūrė'),
        ),
    ]
