# Generated by Django 4.2.7 on 2025-10-29 13:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Vardas')),
                ('last_name', models.CharField(max_length=100, verbose_name='Pavardė')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='El. paštas')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefonas')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Pareigos')),
                ('notes', models.TextField(blank=True, verbose_name='Pastabos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kontaktinis asmuo',
                'verbose_name_plural': 'Kontaktiniai asmenys',
                'db_table': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Pavadinimas')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Įmonės kodas')),
                ('vat_code', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='PVM kodas')),
                ('address', models.TextField(blank=True, verbose_name='Adresas')),
                ('payment_term_days', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Atsiskaitymo terminas (dienos)')),
                ('status', models.CharField(choices=[('active', 'Aktyvus'), ('blocked', 'Užblokuotas')], db_index=True, default='active', max_length=20, verbose_name='Būsena')),
                ('is_supplier', models.BooleanField(db_index=True, default=False, verbose_name='Tiekėjas')),
                ('is_client', models.BooleanField(db_index=True, default=False, verbose_name='Klientas')),
                ('notes', models.TextField(blank=True, verbose_name='Pastabos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='partners.contact', verbose_name='Kontaktinis asmuo')),
            ],
            options={
                'verbose_name': 'Partneris',
                'verbose_name_plural': 'Partneriai',
                'db_table': 'partners',
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['first_name', 'last_name'], name='contacts_first_n_e3c7c9_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['name'], name='partners_name_be6a0f_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['code'], name='partners_code_4a2745_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['status'], name='partners_status_6458e3_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['is_supplier', 'is_client'], name='partners_is_supp_7c0970_idx'),
        ),
    ]
