# Generated by Django 4.2.7 on 2025-11-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_contact_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Vardas'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pavardė'),
        ),
    ]
