# Generated by Django 4.2.7 on 2025-01-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_partner_email_notify_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='email_notify_manager_invoices',
            field=models.BooleanField(default=True, help_text='Jei pažymėta, vadybininkui bus siunčiami pranešimai apie tiekėjo sąskaitas, kurias reikia apmokėti', verbose_name='Siųsti vadybininkui pranešimą apie tiekėjo sąskaitas'),
        ),
    ]

