# Generated by Django 4.2.7 on 2025-12-11 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_partner_email_notify_manager_invoices'),
    ]

    operations = [
        # Atkurti originalius laukus
        migrations.AlterField(
            model_name='contact',
            name='partner',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='contacts',
                to='partners.partner',
                verbose_name='Partneris'
            ),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
