# Generated by Django 4.2.7 on 2025-12-16 15:49

from django.db import migrations, models


def migrate_sender_data(apps, schema_editor):
    """Migrate MailSender data to Contact model"""
    try:
        MailSender = apps.get_model('mail', 'MailSender')
        Contact = apps.get_model('partners', 'Contact')

        print("Migrating sender data from MailSender to Contact...")

        # Get all MailSender records
        senders = MailSender.objects.all()
        migrated_count = 0

        for sender in senders:
            # Try to find existing contact with same email
            existing_contact = Contact.objects.filter(email__iexact=sender.email).first()

            if existing_contact:
                # Update existing contact
                existing_contact.is_trusted = sender.is_trusted
                existing_contact.is_advertising = sender.is_advertising
                if sender.name and not existing_contact.first_name and not existing_contact.last_name:
                    # Set name if contact doesn't have one
                    existing_contact.first_name = sender.name
                existing_contact.save()
                print(f"Updated existing contact: {existing_contact.email}")
            else:
                # Create new contact without partner (orphan contact)
                contact = Contact.objects.create(
                    email=sender.email,
                    first_name=sender.name or '',
                    last_name='',
                    is_trusted=sender.is_trusted,
                    is_advertising=sender.is_advertising,
                    notes=f'Migrated from MailSender: {sender.notes or ""}',
                    phone='',
                    position=''
                )
                print(f"Created new contact: {contact.email}")

            migrated_count += 1

        print(f"Successfully migrated {migrated_count} sender records")

    except Exception as e:
        print(f"Migration error: {e}")
        # Continue with migration even if there's an error


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_partner_email_notify_manager_invoices'),
        ('mail', '0014_mailsender_mailmessage_sender_email_and_more'),  # Ensure MailSender exists
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_advertising',
            field=models.BooleanField(default=False, verbose_name='Reklaminis siuntėjas'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_trusted',
            field=models.BooleanField(default=False, verbose_name='Patikimas siuntėjas'),
        ),
        migrations.RunPython(migrate_sender_data),
    ]
