# Generated by Django 4.2.7 on 2025-12-11 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_auto_20251211_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='partner',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='contacts',
                to='partners.partner',
                verbose_name='Partneris'
            ),
        ),
    ]
