# Generated by Django 4.2.7 on 2025-12-16 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0006_add_sender_classification'),
        ('partners', '0007_auto_20251211_1706'),
    ]

    operations = [
    ]
