# Generated by Django 4.2.7 on 2026-02-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0009_partner_has_code_errors'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['has_code_errors'], name='partners_has_cod_0f5638_idx'),
        ),
    ]
