# Generated by Django 4.2.7 on 2025-10-29 13:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Pavadinimas')),
                ('description', models.TextField(blank=True, verbose_name='Aprašymas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Išlaidų kategorija',
                'verbose_name_plural': 'Išlaidų kategorijos',
                'db_table': 'expense_categories',
            },
        ),
        migrations.CreateModel(
            name='InvoiceNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, unique=True)),
                ('last_number', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sąskaitų numeracijos seka',
                'verbose_name_plural': 'Sąskaitų numeracijos sekos',
                'db_table': 'invoice_number_sequences',
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Sąskaitos numeris')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Neapmokėta'), ('paid', 'Apmokėta'), ('overdue', 'Vėluoja'), ('partially_paid', 'Dalinis apmokėjimas')], db_index=True, default='unpaid', max_length=20, verbose_name='Mokėjimo būsena')),
                ('amount_net', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Suma be PVM')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, verbose_name='PVM tarifas (%)')),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Suma su PVM')),
                ('issue_date', models.DateField(verbose_name='Išrašymo data')),
                ('due_date', models.DateField(verbose_name='Mokėjimo terminas')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Mokėjimo data')),
                ('overdue_days', models.IntegerField(default=0, verbose_name='Vėlavimo dienos')),
                ('notes', models.TextField(blank=True, verbose_name='Pastabos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pirkimo sąskaita',
                'verbose_name_plural': 'Pirkimo sąskaitos',
                'db_table': 'purchase_invoices',
            },
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Sąskaitos numeris')),
                ('invoice_type', models.CharField(choices=[('pre_invoice', 'Pro forma sąskaita'), ('final', 'Galutinė sąskaita'), ('credit', 'Kreditinė sąskaita'), ('proforma', 'Proforma')], default='final', max_length=20, verbose_name='Sąskaitos tipas')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Neapmokėta'), ('paid', 'Apmokėta'), ('overdue', 'Vėluoja'), ('partially_paid', 'Dalinis apmokėjimas')], db_index=True, default='unpaid', max_length=20, verbose_name='Mokėjimo būsena')),
                ('amount_net', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Suma be PVM')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, verbose_name='PVM tarifas (%)')),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Suma su PVM')),
                ('issue_date', models.DateField(verbose_name='Išrašymo data')),
                ('due_date', models.DateField(verbose_name='Mokėjimo terminas')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Mokėjimo data')),
                ('overdue_days', models.IntegerField(default=0, verbose_name='Vėlavimo dienos')),
                ('notes', models.TextField(blank=True, verbose_name='Pastabos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_invoices', to='invoices.salesinvoice', verbose_name='Kreditinė sąskaita')),
                ('partner', models.ForeignKey(limit_choices_to={'is_client': True}, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='partners.partner', verbose_name='Klientas')),
            ],
            options={
                'verbose_name': 'Pardavimo sąskaita',
                'verbose_name_plural': 'Pardavimo sąskaitos',
                'db_table': 'sales_invoices',
            },
        ),
    ]
