# Generated by Django 4.2.7 on 2025-10-29 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        ('invoices', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='related_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='orders.order', verbose_name='Susijęs užsakymas'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='expense_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoices', to='invoices.expensecategory', verbose_name='Išlaidų kategorija'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='partner',
            field=models.ForeignKey(limit_choices_to={'is_supplier': True}, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='partners.partner', verbose_name='Tiekėjas'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='related_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoices', to='orders.order', verbose_name='Susijęs užsakymas'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['invoice_number'], name='sales_invoi_invoice_3ac144_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['partner'], name='sales_invoi_partner_e1864c_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['payment_status'], name='sales_invoi_payment_39abb0_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['due_date'], name='sales_invoi_due_dat_07e1d0_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['invoice_number'], name='purchase_in_invoice_8aefda_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['partner'], name='purchase_in_partner_3971cb_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['payment_status'], name='purchase_in_payment_4c015e_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['due_date'], name='purchase_in_due_dat_a07ecd_idx'),
        ),
    ]
