# Generated by Django 4.2.7 on 2025-10-29 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='received_invoice_number',
            field=models.CharField(db_index=True, default='', max_length=50, verbose_name='Tiekėjo sąskaitos numeris'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='expense_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='invoices.expensecategory', verbose_name='Išlaidų kategorija'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_number',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Sistemos sąskaitos numeris'),
        ),
    ]
