# Generated by Django 4.2.7 on 2025-10-29 19:32

import apps.invoices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_purchaseinvoice_received_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.invoices.models.purchase_invoice_file_path, verbose_name='Sąskaitos failas (PDF)'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='received_date',
            field=models.DateField(blank=True, null=True, verbose_name='Gavimo data'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='issue_date',
            field=models.DateField(verbose_name='Tiekėjo sąskaitos išrašymo data'),
        ),
    ]
