# Generated by Django 4.2.7 on 2025-10-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_purchaseinvoice_invoice_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Sistemos sąskaitos numeris (neprivalomas)'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='received_invoice_number',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Tiekėjo sąskaitos numeris'),
        ),
    ]
