# Generated by Django 4.2.7 on 2025-10-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_alter_purchaseinvoice_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='display_options',
            field=models.JSONField(blank=True, default=dict, help_text='JSON objektas su pasirinkimais, ką rodyti sąskaitoje: {"show_cargo_info": true, "show_cargo_details": true, "show_carriers": true, "show_carrier_details": true, "show_prices": true, "show_price_details": true}', verbose_name='Rodymo pasirinkimai'),
        ),
    ]
