# Generated by Django 4.2.7 on 2025-10-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_add_display_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='manual_lines',
            field=models.JSONField(blank=True, default=list, help_text='JSON masyvas: [{"description": "Paslauga", "amount_net": 100.00}]', verbose_name='Rankinės eilutės'),
        ),
    ]
