# Generated by Django 4.2.7 on 2025-10-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_salesinvoice_manual_lines'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLineTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, unique=True, verbose_name='Aprašymas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sąskaitos eilutės šablonas',
                'verbose_name_plural': 'Sąskaitos eilučių šablonai',
                'db_table': 'invoice_line_templates',
            },
        ),
    ]
