# Generated by Django 4.2.7 on 2025-10-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_invoicelinetemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicelinetemplate',
            options={'ordering': ['description'], 'verbose_name': 'Sąskaitos eilutės šablonas', 'verbose_name_plural': 'Sąskaitos eilučių šablonai'},
        ),
        migrations.AddField(
            model_name='invoicelinetemplate',
            name='usage_count',
            field=models.IntegerField(default=0, verbose_name='Naudojimų skaičius'),
        ),
    ]
