# Generated by Django 4.2.7 on 2025-10-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_alter_invoicelinetemplate_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['created_at'], name='sales_invoi_created_e9b75b_idx'),
        ),
    ]
