# Generated by Django 4.2.7 on 2025-10-31 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_salesinvoice_sales_invoi_created_e9b75b_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoiceLineTemplate',
        ),
        migrations.RemoveIndex(
            model_name='salesinvoice',
            name='sales_invoi_created_e9b75b_idx',
        ),
    ]
