# Generated by Django 4.2.7 on 2025-10-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_delete_invoicelinetemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='vat_rate_article',
            field=models.CharField(blank=True, help_text='PVM įstatymo straipsnis (pvz. 5 str. 7 d., 6 str.)', max_length=255, verbose_name='PVM straipsnis'),
        ),
    ]
