# Generated by Django 4.2.7 on 2025-10-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_salesinvoice_vat_rate_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='visible_items_indexes',
            field=models.JSONField(blank=True, default=list, help_text='JSON masyvas su eilučių indeksais, kurie turi būti rodomi HTML peržiūroje: [0, 1, 3]', verbose_name='Matomų eilučių indeksai'),
        ),
    ]
