# Generated by Django 4.2.7 on 2025-11-07 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_order_other_costs_order_receiver_route_to_and_more'),
        ('invoices', '0013_salesinvoice_visible_items_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='related_orders',
            field=models.ManyToManyField(blank=True, related_name='purchase_invoices_m2m', to='orders.order', verbose_name='Susiję užsakymai'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='related_orders_amounts',
            field=models.JSONField(blank=True, default=list, help_text='JSON masyvas su užsakymų sumomis: [{"order_id": 1, "amount": "100.00"}, ...]', verbose_name='Užsakymų sumos'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='related_order',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Naudokite related_orders. Palikta suderinamumui.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoices', to='orders.order', verbose_name='Susijęs užsakymas'),
        ),
    ]
