# Generated by Django 4.2.7 on 2025-11-19 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_purchaseinvoice_related_orders_and_more'),
    ]

    operations = [
    ]
