# Generated by Django 4.2.7 on 2025-11-21 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_alter_autocompletesuggestion_field_type_and_more'),
        ('invoices', '0019_salesinvoice_related_orders_m2m'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salesinvoiceorder',
            name='unique_sales_invoice_order',
        ),
        migrations.RenameIndex(
            model_name='invoicereminder',
            new_name='invoice_rem_invoice_e483aa_idx',
            old_name='invoice_rem_invoice_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='invoicereminder',
            new_name='invoice_rem_last_se_177a39_idx',
            old_name='invoice_rem_last_se_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='salesinvoiceorder',
            new_name='sales_invoi_invoice_93193c_idx',
            old_name='sales_invoice_orders_inv_ord_idx',
        ),
        migrations.RenameIndex(
            model_name='salesinvoiceorder',
            new_name='sales_invoi_order_i_58245c_idx',
            old_name='sales_invoice_orders_order_idx',
        ),
        migrations.AlterField(
            model_name='invoicenumbersequence',
            name='last_number',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/purchase/', verbose_name='Sąskaitos failas (PDF)'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='overdue_days',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Vėlavimo dienos'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='overdue_days',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Vėlavimo dienos'),
        ),
        migrations.AlterUniqueTogether(
            name='salesinvoiceorder',
            unique_together={('invoice', 'order')},
        ),
    ]
