# Generated by Django 4.2.7 on 2026-01-10 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_purchaseinvoice_related_orders_and_more'),
        ('invoices', '0020_remove_salesinvoiceorder_unique_sales_invoice_order_and_more'),
    ]

    operations = [
    ]
