# Generated by Django 4.2.7 on 2026-01-16 14:37

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0065_change_routestop_dates_to_datetime'),
        ('mail', '0019_add_related_purchase_invoice_to_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0021_merge_20260110_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Apmokėta suma')),
                ('payment_date', models.DateField(verbose_name='Mokėjimo data')),
                ('payment_method', models.CharField(blank=True, help_text='pvz. Banko pavedimas, Grynieji, Kortelė', max_length=50, verbose_name='Mokėjimo būdas')),
                ('notes', models.TextField(blank=True, verbose_name='Pastabos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sąskaitos mokėjimas',
                'verbose_name_plural': 'Sąskaitų mokėjimai',
                'db_table': 'invoice_payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='salesinvoice',
            options={'ordering': ['-issue_date', '-created_at'], 'verbose_name': 'Pardavimo sąskaita', 'verbose_name_plural': 'Pardavimo sąskaitos'},
        ),
        migrations.AlterModelOptions(
            name='salesinvoiceorder',
            options={'verbose_name': 'Sąskaitos užsakymas', 'verbose_name_plural': 'Sąskaitos užsakymai'},
        ),
        migrations.RemoveIndex(
            model_name='salesinvoiceorder',
            name='sales_invoi_invoice_93193c_idx',
        ),
        migrations.RemoveIndex(
            model_name='salesinvoiceorder',
            name='sales_invoi_order_i_58245c_idx',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='display_options',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='visible_items_indexes',
        ),
        migrations.RemoveField(
            model_name='salesinvoiceorder',
            name='amount_net',
        ),
        migrations.RemoveField(
            model_name='salesinvoiceorder',
            name='amount_total',
        ),
        migrations.RemoveField(
            model_name='salesinvoiceorder',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='related_attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoices', to='mail.mailattachment', verbose_name='Susijęs priedas'),
        ),
        migrations.AddField(
            model_name='salesinvoiceorder',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kiek šis užsakymas sudaro iš visos sąskaitos sumos', max_digits=10, null=True, verbose_name='Suma'),
        ),
        migrations.AlterField(
            model_name='invoicenumbersequence',
            name='last_number',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Paskutinis numeris'),
        ),
        migrations.AlterField(
            model_name='invoicenumbersequence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atnaujinta'),
        ),
        migrations.AlterField(
            model_name='invoicenumbersequence',
            name='year',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='Metai'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='manual_lines',
            field=models.JSONField(blank=True, default=list, help_text='JSON masyvas su eilutėmis: [{"description": "...", "quantity": 1, "price": "100.00", ...}, ...]', verbose_name='Rankinės eilutės'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='salesinvoiceorder',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_orders', to='invoices.salesinvoice'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_sales_invoices', to='orders.order'),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL, verbose_name='Sukūrė'),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='purchase_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='invoices.purchaseinvoice', verbose_name='Gauta sąskaita'),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='sales_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='invoices.salesinvoice', verbose_name='Išrašyta sąskaita'),
        ),
        migrations.AddIndex(
            model_name='invoicepayment',
            index=models.Index(fields=['sales_invoice'], name='invoice_pay_sales_i_522133_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicepayment',
            index=models.Index(fields=['purchase_invoice'], name='invoice_pay_purchas_a22b32_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicepayment',
            index=models.Index(fields=['payment_date'], name='invoice_pay_payment_de7f11_idx'),
        ),
    ]
