# Generated by Django 4.2.7 on 2026-01-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0022_add_invoice_payment_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='display_options',
            field=models.JSONField(blank=True, default=dict, help_text='JSON objektas su rodymo parinktimis', verbose_name='Rodymo parinktys'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='visible_items_indexes',
            field=models.JSONField(blank=True, default=list, help_text='JSON masyvas su matomų elementų indeksais', verbose_name='Matomų elementų indeksai'),
        ),
    ]
