# Generated by Django 4.2.7 on 2025-10-29 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Įmonės pavadinimas')),
                ('code', models.CharField(max_length=50, verbose_name='Įmonės kodas')),
                ('vat_code', models.CharField(blank=True, max_length=50, verbose_name='PVM kodas')),
                ('address', models.TextField(verbose_name='Adresas')),
                ('city', models.CharField(max_length=100, verbose_name='Miestas')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Pašto kodas')),
                ('country', models.CharField(default='Lietuva', max_length=100, verbose_name='Šalis')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefonas')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='El. paštas')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Banko pavadinimas')),
                ('bank_account', models.CharField(blank=True, max_length=50, verbose_name='Banko sąskaita')),
                ('bank_code', models.CharField(blank=True, max_length=20, verbose_name='Banko kodas')),
                ('notes', models.TextField(blank=True, verbose_name='Pastabos')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Įmonės informacija',
                'verbose_name_plural': 'Įmonės informacija',
                'db_table': 'company_info',
            },
        ),
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_vat_rate', models.DecimalField(decimal_places=2, default=21.0, max_digits=5, verbose_name='Numatytasis PVM tarifas (%)')),
                ('default_payment_term_days', models.IntegerField(default=30, verbose_name='Numatytasis mokėjimo terminas (dienos)')),
                ('invoice_prefix_sales', models.CharField(default='SF', max_length=10, verbose_name='Pardavimo sąskaitų prefiksas')),
                ('invoice_prefix_purchase', models.CharField(default='PI', max_length=10, verbose_name='Pirkimo sąskaitų prefiksas')),
                ('invoice_footer_text', models.TextField(blank=True, verbose_name='Sąskaitos apačios tekstas')),
                ('auto_numbering', models.BooleanField(default=True, verbose_name='Automatinis numeravimas')),
                ('notes', models.TextField(blank=True, verbose_name='Pastabos')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sąskaitų nustatymai',
                'verbose_name_plural': 'Sąskaitų nustatymai',
                'db_table': 'invoice_settings',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('lt', 'Lietuvių'), ('en', 'English')], default='lt', max_length=10, verbose_name='Kalba')),
                ('date_format', models.CharField(choices=[('YYYY-MM-DD', 'YYYY-MM-DD'), ('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY')], default='YYYY-MM-DD', max_length=20, verbose_name='Datos formatas')),
                ('timezone', models.CharField(default='Europe/Vilnius', max_length=50, verbose_name='Laiko juosta')),
                ('items_per_page', models.IntegerField(default=100, verbose_name='Elementų per puslapį')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to=settings.AUTH_USER_MODEL, verbose_name='Vartotojas')),
            ],
            options={
                'verbose_name': 'Vartotojo nustatymai',
                'verbose_name_plural': 'Vartotojo nustatymai',
                'db_table': 'user_settings',
            },
        ),
    ]
