# Generated by Django 4.2.7 on 2025-10-29 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesettings',
            name='invoice_number_width',
            field=models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Sąskaitos numerio skaitmenų skaičius'),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='invoice_prefix_sales',
            field=models.CharField(default='LOG', max_length=10, verbose_name='Pardavimo sąskaitų prefiksas'),
        ),
    ]
