# Generated by Django 4.2.7 on 2025-10-29 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_invoicesettings_invoice_number_width_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicesettings',
            name='invoice_prefix_purchase',
        ),
    ]
