# Generated by Django 4.2.7 on 2025-10-29 20:53

import apps.settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_remove_invoicesettings_invoice_prefix_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, help_text='Įmonės logotipas, kuris bus rodomas sąskaitose', null=True, upload_to=apps.settings.models.company_logo_upload_path, verbose_name='Logotipas'),
        ),
    ]
