# Generated by Django 4.2.7 on 2025-10-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_companyinfo_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesettings',
            name='default_display_options',
            field=models.JSONField(blank=True, default=dict, help_text='JSON objektas su numatytosiomis vertėmis, ką rodyti sąskaitoje: {"show_cargo_info": true, "show_cargo_weight": true, ...}', verbose_name='Numatytieji rodymo pasirinkimai'),
        ),
    ]
