# Generated by Django 4.2.7 on 2025-10-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_invoicesettings_default_display_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='El. paštas'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Vardas'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Pavardė'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefonas'),
        ),
    ]
