# Generated by Django 4.2.7 on 2025-10-30 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_usersettings_email_usersettings_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number_width', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Užsakymo numerio skaitmenų skaičius (NNN)')),
                ('auto_numbering', models.BooleanField(default=True, verbose_name='Automatinis užsakymų numeravimas')),
                ('notes', models.TextField(blank=True, verbose_name='Pastabos')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Užsakymų nustatymai',
                'verbose_name_plural': 'Užsakymų nustatymai',
                'db_table': 'order_settings',
            },
        ),
    ]
