# Generated by Django 4.2.7 on 2025-10-31 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_ordersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersettings',
            name='my_price_percentage',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Automatiškai apskaičiuojama "mano kaina" kaip šis procentas nuo bendros vežėjų/sandėlių kainos', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Mano kainos procentas nuo bendros užsakymo kainos (%)'),
        ),
    ]
