# Generated by Django 4.2.7 on 2025-10-31 15:31

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_ordersettings_my_price_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PVMRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='PVM tarifas (%)')),
                ('article', models.CharField(blank=True, help_text='PVM įstatymo straipsnis (pvz. 5 str. 7 d., 6 str., ir t.t.)', max_length=255, verbose_name='Straipsnis')),
                ('is_active', models.BooleanField(default=True, help_text='Jei neaktyvus, nebus rodomas sąskaitų formose', verbose_name='Aktyvus')),
                ('sequence_order', models.IntegerField(default=0, help_text='Nustato tvarką rodant sąraše', verbose_name='Eiliškumas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PVM tarifas su straipsniu',
                'verbose_name_plural': 'PVM tarifai su straipsniais',
                'db_table': 'pvm_rates',
                'ordering': ['sequence_order', 'rate'],
            },
        ),
        migrations.AlterField(
            model_name='ordersettings',
            name='my_price_percentage',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Automatiškai apskaičiuojama "mano kaina" kaip šis procentas nuo bendros sumos (vežėjų/sandėlių kainos + kitos išlaidos)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Mano kainos procentas nuo bendros užsakymo kainos (%)'),
        ),
    ]
