# Generated by Django 4.2.7 on 2025-11-02 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_pvmrate_alter_ordersettings_my_price_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_enabled', models.BooleanField(default=False, help_text='Jei įjungta, sistema siųs el. laiškus', verbose_name='Įjungti el. laiškų siuntimą')),
                ('smtp_host', models.CharField(blank=True, help_text='Pvz.: smtp.gmail.com', max_length=255, verbose_name='SMTP serveris')),
                ('smtp_port', models.IntegerField(default=587, help_text='Dažniausiai: 587 (TLS) arba 465 (SSL)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='SMTP portas')),
                ('smtp_use_tls', models.BooleanField(default=True, help_text='Jei ne, naudojamas SSL', verbose_name='Naudoti TLS')),
                ('smtp_username', models.CharField(blank=True, max_length=255, verbose_name='SMTP naudotojas')),
                ('smtp_password', models.CharField(blank=True, help_text='Saugojamas užšifruotas', max_length=255, verbose_name='SMTP slaptažodis')),
                ('smtp_from_email', models.EmailField(blank=True, max_length=254, verbose_name='Numatytasis siuntėjas (el. paštas)')),
                ('smtp_from_name', models.CharField(blank=True, max_length=255, verbose_name='Numatytasis siuntėjas (vardas)')),
                ('email_notify_overdue_invoices', models.BooleanField(default=False, help_text='Automatiškai siųsti priminimus apie vėluojančias sąskaitas', verbose_name='Siųsti priminimą apie vėluojančias sąskaitas')),
                ('email_notify_overdue_days_before', models.IntegerField(default=3, help_text='Kiek dienų prieš terminą siųsti priminimą', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Priminimas X dienų prieš terminą')),
                ('email_notify_unpaid_invoices', models.BooleanField(default=False, help_text='Periodiškai siųsti priminimus apie neapmokėtas sąskaitas', verbose_name='Siųsti priminimą apie neapmokėtas sąskaitas')),
                ('email_notify_unpaid_interval_days', models.IntegerField(default=7, help_text='Kas kiek dienų siųsti priminimą', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Priminimo intervalas (dienos)')),
                ('email_notify_new_orders', models.BooleanField(default=False, help_text='Siųsti pranešimą vadybininkui apie naują užsakymą', verbose_name='Pranešti apie naujus užsakymus')),
                ('email_notify_payment_received', models.BooleanField(default=False, help_text='Siųsti pranešimą kai gautas mokėjimas', verbose_name='Pranešti apie gautus mokėjimus')),
                ('toast_duration_ms', models.IntegerField(default=3500, help_text='Kiek laiko rodyti pranešimą (1000-10000 ms)', validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(10000)], verbose_name='Pranešimų trukmė (milisekundės)')),
                ('toast_position', models.CharField(choices=[('top', 'Viršuje'), ('center', 'Centre'), ('bottom', 'Apačioje')], default='center', max_length=20, verbose_name='Pranešimų pozicija')),
                ('toast_enable_sound', models.BooleanField(default=False, help_text='Groti garso signalą rodant pranešimą', verbose_name='Garso signalas')),
                ('toast_success_color', models.CharField(default='#28a745', help_text='Hex spalvos kodas, pvz.: #28a745', max_length=7, verbose_name='Sėkmės pranešimų spalva')),
                ('toast_error_color', models.CharField(default='#dc3545', help_text='Hex spalvos kodas, pvz.: #dc3545', max_length=7, verbose_name='Klaidos pranešimų spalva')),
                ('toast_info_color', models.CharField(default='#17a2b8', help_text='Hex spalvos kodas, pvz.: #17a2b8', max_length=7, verbose_name='Informacijos pranešimų spalva')),
                ('notes', models.TextField(blank=True, verbose_name='Pastabos')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pranešimų nustatymai',
                'verbose_name_plural': 'Pranešimų nustatymai',
                'db_table': 'notification_settings',
            },
        ),
    ]
