# Generated by Django 4.2.7 on 2025-11-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_ordersettings_payment_terms_and_obligations'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='correspondence_address',
            field=models.TextField(blank=True, help_text='Jei nenurodytas, bus naudojamas pagrindinis adresas', verbose_name='Adresas korespondencijai'),
        ),
    ]
