# Generated by Django 4.2.7 on 2025-11-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_expeditionsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersettings',
            name='clear_autocomplete_on_reset',
            field=models.BooleanField(default=False, verbose_name='Išvalyti autocomplete duomenis'),
        ),
        migrations.AddField(
            model_name='ordersettings',
            name='order_prefix',
            field=models.CharField(blank=True, default='', help_text='Prefiksas, kuris bus pridėtas numerio pradžioje (pvz.: 2025). Jei tuščias, bus naudojami dabartiniai metai.', max_length=10, verbose_name='Užsakymo numerio prefiksas'),
        ),
    ]
