# Generated by Django 4.2.7 on 2025-11-11 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0016_add_order_prefix'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "ALTER TABLE `invoice_settings` MODIFY COLUMN `invoice_footer_text` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
                "ALTER TABLE `invoice_settings` MODIFY COLUMN `notes` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            ],
            reverse_sql=[
                "ALTER TABLE `invoice_settings` MODIFY COLUMN `invoice_footer_text` TEXT;",
                "ALTER TABLE `invoice_settings` MODIFY COLUMN `notes` TEXT;",
            ],
        ),
    ]
