# Generated by Django 4.2.7 on 2025-11-14 12:46

import apps.settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0017_fix_invoice_footer_text_charset'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='signature_image',
            field=models.ImageField(blank=True, help_text='Parašo arba stampo paveikslėlis, naudojamas dokumentuose', null=True, upload_to=apps.settings.models.user_signature_upload_path, verbose_name='Parašo/Stampo paveikslėlis'),
        ),
    ]
