# Generated by Django 4.2.7 on 2025-11-19 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_companyinfo_correspondence_address'),
        ('settings', '0018_add_user_signature_image'),
    ]

    operations = [
    ]
