# Generated by Django 4.2.7 on 2025-11-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0027_notificationsettings_overdue_reminder_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsettings',
            name='email_notify_new_orders',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='email_notify_overdue_days_before',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='email_notify_overdue_invoices',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='email_notify_payment_received',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='email_notify_unpaid_invoices',
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body_text',
            field=models.TextField(help_text='El. laiško turinys paprastu tekstu. Galite naudoti kintamuosius: {invoice_number}, {order_number}, {partner_name}, {amount}, {amount_net}, {amount_total}, {vat_rate}, {issue_date}, {due_date}, {overdue_days}, {payment_status}, {manager_name}, {other_unpaid_invoices}', verbose_name='Turinys (tekstas)'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(help_text='El. laiško antraštė. Galite naudoti kintamuosius: {invoice_number}, {order_number}, {partner_name}, {amount}, {amount_net}, {amount_total}, {vat_rate}, {issue_date}, {due_date}, {overdue_days}, {payment_status}, {manager_name}, {other_unpaid_invoices}', max_length=512, verbose_name='Antraštė'),
        ),
        migrations.AlterField(
            model_name='uisettings',
            name='status_colors',
            field=models.JSONField(blank=True, default=dict, help_text='JSON objektas su spalvomis pagal būsenas: {"invoices": {"paid": "#28a745", "not_paid": "#dc3545", ...}, "expeditions": {"new": "#17a2b8", ...}, "orders": {"new": "#17a2b8", ...}, "payment_colors": {"no_invoice": "#000000", "unpaid": "#dc3545", "partially_paid": "#ffc107", "paid": "#28a745"}}', verbose_name='Būsenų spalvos'),
        ),
    ]
