# Generated by Django 4.2.7 on 2026-01-06 11:55

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0028_remove_notificationsettings_email_notify_new_orders_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseExpeditionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expedition_prefix', models.CharField(default='WH-', max_length=10, verbose_name='Sandėlių ekspedicijos numerio prefiksas')),
                ('expedition_number_width', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Sandėlių ekspedicijos numerio skaitmenų skaičius (NNNNN)')),
                ('auto_numbering', models.BooleanField(default=True, verbose_name='Automatinis sandėlių ekspedicijų numeravimas')),
            ],
            options={
                'verbose_name': 'Sandėlių ekspedicijos nustatymai',
                'verbose_name_plural': 'Sandėlių ekspedicijos nustatymai',
            },
        ),
        migrations.CreateModel(
            name='CostExpeditionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expedition_prefix', models.CharField(default='COST-', max_length=10, verbose_name='Išlaidų numerio prefiksas')),
                ('expedition_number_width', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Išlaidų numerio skaitmenų skaičius (NNNNN)')),
                ('auto_numbering', models.BooleanField(default=True, verbose_name='Automatinis išlaidų numeravimas')),
            ],
            options={
                'verbose_name': 'Išlaidų nustatymai',
                'verbose_name_plural': 'Išlaidų nustatymai',
            },
        ),
    ]
