# Generated by Django 4.2.7 on 2026-01-06 11:56

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0029_add_warehouse_and_cost_settings_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpeditionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expedition_prefix', models.CharField(default='E', max_length=10, verbose_name='Vežėjų ekspedicijos numerio prefiksas')),
                ('expedition_number_width', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Vežėjų ekspedicijos numerio skaitmenų skaičius (NNNNN)')),
                ('auto_numbering', models.BooleanField(default=True, verbose_name='Automatinis vežėjų ekspedicijų numeravimas')),
            ],
            options={
                'verbose_name': 'Vežėjų ekspedicijos nustatymai',
                'verbose_name_plural': 'Vežėjų ekspedicijos nustatymai',
            },
        ),
    ]
