# Generated by Django 4.2.7 on 2026-01-10 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0031_add_timestamps_to_expedition_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costexpeditionsettings',
            options={'verbose_name': '1. Ekspedicijos nustatymai', 'verbose_name_plural': '1. Ekspedicijos nustatymai'},
        ),
        migrations.AlterModelOptions(
            name='expeditionsettings',
            options={},
        ),
        migrations.AlterModelOptions(
            name='warehouseexpeditionsettings',
            options={'verbose_name': '2. Sandėlių nustatymai', 'verbose_name_plural': '2. Sandėlių nustatymai'},
        ),
        migrations.AddField(
            model_name='costexpeditionsettings',
            name='carrier_obligations',
            field=models.JSONField(blank=True, default=list, help_text='Sąrašas punktų, pvz: [{"text": "Vežėjas privalomai turi turėti..."}]', verbose_name='Vežėjo teisės ir pareigos'),
        ),
        migrations.AddField(
            model_name='costexpeditionsettings',
            name='client_obligations',
            field=models.JSONField(blank=True, default=list, help_text='Sąrašas punktų, pvz: [{"text": "Pateikia Vežėjui..."}]', verbose_name='Užsakovo teisės ir pareigos'),
        ),
        migrations.AddField(
            model_name='costexpeditionsettings',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Pastabos'),
        ),
        migrations.AddField(
            model_name='costexpeditionsettings',
            name='payment_terms',
            field=models.TextField(blank=True, default='30 kalendorinių dienų po PVM sąskaitos-faktūros ir važtaraščio su krovinio gavimo data ir gavėjo vardu, pavarde, parašu gavimo.', help_text='Apmokėjimo terminas, kuris bus rodomas ekspedicijos sutartyje. Naudojamas kaip numatytasis, jei vežėjo modelyje payment_terms nėra nustatytas.', verbose_name='Apmokėjimo terminas'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='email_notify_due_soon_days_before',
            field=models.IntegerField(default=3, help_text='Kiek dienų prieš terminą siųsti priminimą', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Priminimas X dienų prieš terminą'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='email_notify_due_soon_enabled',
            field=models.BooleanField(default=False, help_text='Automatiškai siųsti priminimus apie artėjantį apmokėjimo terminą', verbose_name='Siųsti priminimą apie artėjantį terminą'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='email_notify_due_soon_min_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Siųsti tik jei suma didesnė už nurodytą (0 = be apribojimų)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimali suma (artėja terminas)'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='email_notify_due_soon_recipient',
            field=models.CharField(choices=[('client', 'Klientui'), ('manager', 'Vadybininkui'), ('both', 'Abiems')], default='client', help_text='Kam siųsti priminimą apie artėjantį terminą', max_length=20, verbose_name='Kam siųsti (artėja terminas)'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='email_notify_expedition_status_changed_enabled',
            field=models.BooleanField(default=False, help_text='Siųsti pranešimą kai ekspedicijos statusas pasikeičia', verbose_name='Pranešti apie ekspedicijos statuso pakeitimą'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='email_notify_expedition_status_changed_recipient',
            field=models.CharField(choices=[('carrier', 'Vežėjui'), ('manager', 'Vadybininkui'), ('both', 'Abiems')], default='manager', help_text='Kam siųsti pranešimą apie ekspedicijos statuso pakeitimą', max_length=20, verbose_name='Kam siųsti (ekspedicijos statuso pakeitimas)'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='email_notify_high_amount_invoice_enabled',
            field=models.BooleanField(default=False, help_text='Siųsti pranešimą apie sąskaitas, kurių suma viršija nustatytą ribą', verbose_name='Pranešti apie didelės sumos sąskaitas'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='email_notify_high_amount_recipient',
            field=models.CharField(choices=[('client', 'Klientui'), ('manager', 'Vadybininkui'), ('both', 'Abiems')], default='manager', help_text='Kam siųsti pranešimą apie didelės sumos sąskaitas', max_length=20, verbose_name='Kam siųsti (didelė suma)'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='email_notify_high_amount_threshold',
            field=models.DecimalField(decimal_places=2, default=10000, help_text='Siųsti pranešimą jei sąskaitos suma viršija šią ribą', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sumos riba'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='email_notify_new_expedition_enabled',
            field=models.BooleanField(default=False, help_text='Siųsti pranešimą apie naują ekspediciją', verbose_name='Pranešti apie naujas ekspedicijas'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='email_notify_new_expedition_recipient',
            field=models.CharField(choices=[('carrier', 'Vežėjui'), ('manager', 'Vadybininkui'), ('both', 'Abiems')], default='manager', help_text='Kam siųsti pranešimą apie naują ekspediciją', max_length=20, verbose_name='Kam siųsti (nauja ekspedicija)'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='email_notify_new_order_enabled',
            field=models.BooleanField(default=False, help_text='Siųsti pranešimą apie naują užsakymą', verbose_name='Pranešti apie naujus užsakymus'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='email_notify_new_order_recipient',
            field=models.CharField(choices=[('client', 'Klientui'), ('manager', 'Vadybininkui'), ('both', 'Abiems')], default='manager', help_text='Kam siųsti pranešimą apie naują užsakymą', max_length=20, verbose_name='Kam siųsti (naujas užsakymas)'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='email_notify_order_status_changed_enabled',
            field=models.BooleanField(default=False, help_text='Siųsti pranešimą kai užsakymo statusas pasikeičia', verbose_name='Pranešti apie užsakymo statuso pakeitimą'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='email_notify_order_status_changed_recipient',
            field=models.CharField(choices=[('client', 'Klientui'), ('manager', 'Vadybininkui'), ('both', 'Abiems')], default='manager', help_text='Kam siųsti pranešimą apie užsakymo statuso pakeitimą', max_length=20, verbose_name='Kam siųsti (statuso pakeitimas)'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='email_notify_overdue_enabled',
            field=models.BooleanField(default=False, help_text='Automatiškai siųsti priminimus apie vėluojančias sąskaitas', verbose_name='Siųsti priminimą apie vėluojančias sąskaitas'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='email_notify_overdue_interval_days',
            field=models.IntegerField(default=7, help_text='Kas kiek dienų siųsti priminimą', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Priminimo intervalas (dienos)'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='email_notify_overdue_max_days',
            field=models.IntegerField(default=365, help_text='Siųsti tik jei vėlavimas mažesnis už nurodytą dienų skaičių (0 = be apribojimų)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)], verbose_name='Maksimalus vėlavimas (dienos)'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='email_notify_overdue_min_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Siųsti tik jei suma didesnė už nurodytą (0 = be apribojimų)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimali suma (vėluojama)'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='email_notify_overdue_min_days',
            field=models.IntegerField(default=1, help_text='Siųsti tik jei vėlavimas didesnis už nurodytą dienų skaičių', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)], verbose_name='Minimalus vėlavimas (dienos)'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='email_notify_overdue_recipient',
            field=models.CharField(choices=[('client', 'Klientui'), ('manager', 'Vadybininkui'), ('both', 'Abiems')], default='client', help_text='Kam siųsti priminimą apie vėluojančias sąskaitas', max_length=20, verbose_name='Kam siųsti (vėluojama)'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='email_notify_partial_payment_enabled',
            field=models.BooleanField(default=False, help_text='Siųsti pranešimą kai gautas dalinis mokėjimas', verbose_name='Pranešti apie dalinius mokėjimus'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='email_notify_partial_payment_recipient',
            field=models.CharField(choices=[('client', 'Klientui'), ('manager', 'Vadybininkui'), ('both', 'Abiems')], default='manager', help_text='Kam siųsti pranešimą apie dalinį mokėjimą', max_length=20, verbose_name='Kam siųsti (dalinis mokėjimas)'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='email_notify_payment_received_enabled',
            field=models.BooleanField(default=False, help_text='Siųsti pranešimą kai gautas mokėjimas', verbose_name='Pranešti apie gautus mokėjimus'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='email_notify_payment_received_min_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Siųsti tik jei suma didesnė už nurodytą (0 = be apribojimų)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimali suma (mokėjimas)'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='email_notify_payment_received_recipient',
            field=models.CharField(choices=[('client', 'Klientui'), ('manager', 'Vadybininkui'), ('both', 'Abiems')], default='manager', help_text='Kam siųsti pranešimą apie gautą mokėjimą', max_length=20, verbose_name='Kam siųsti (gautas mokėjimas)'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='email_notify_unpaid_enabled',
            field=models.BooleanField(default=False, help_text='Periodiškai siųsti priminimus apie neapmokėtas sąskaitas', verbose_name='Siųsti priminimą apie neapmokėtas sąskaitas'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='email_notify_unpaid_min_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Siųsti tik jei suma didesnė už nurodytą (0 = be apribojimų)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimali suma (neapmokėta)'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='email_notify_unpaid_recipient',
            field=models.CharField(choices=[('client', 'Klientui'), ('manager', 'Vadybininkui'), ('both', 'Abiems')], default='client', help_text='Kam siųsti priminimą apie neapmokėtas sąskaitas', max_length=20, verbose_name='Kam siųsti (neapmokėta)'),
        ),
        migrations.AlterModelTable(
            name='costexpeditionsettings',
            table='expedition_settings',
        ),
    ]
