# Generated by Django 4.2.7 on 2026-01-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0032_alter_costexpeditionsettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costexpeditionsettings',
            name='payment_terms_en',
            field=models.TextField(blank=True, help_text='Apmokėjimo terminas anglų kalba', verbose_name='Apmokėjimo terminas (EN)'),
        ),
        migrations.AddField(
            model_name='costexpeditionsettings',
            name='payment_terms_ru',
            field=models.TextField(blank=True, help_text='Apmokėjimo terminas rusų kalba', verbose_name='Apmokėjimo terminas (RU)'),
        ),
        migrations.AddField(
            model_name='ordersettings',
            name='payment_terms_en',
            field=models.TextField(blank=True, help_text='Apmokėjimo terminas anglų kalba', verbose_name='Apmokėjimo terminas (EN)'),
        ),
        migrations.AddField(
            model_name='ordersettings',
            name='payment_terms_ru',
            field=models.TextField(blank=True, help_text='Apmokėjimo terminas rusų kalba', verbose_name='Apmokėjimo terminas (RU)'),
        ),
        migrations.AlterField(
            model_name='costexpeditionsettings',
            name='carrier_obligations',
            field=models.JSONField(blank=True, default=list, help_text='Sąrašas punktų, pvz: [{"text": "...", "text_en": "...", "text_ru": "..."}]', verbose_name='Vežėjo teisės ir pareigos'),
        ),
        migrations.AlterField(
            model_name='costexpeditionsettings',
            name='client_obligations',
            field=models.JSONField(blank=True, default=list, help_text='Sąrašas punktų, pvz: [{"text": "...", "text_en": "...", "text_ru": "..."}]', verbose_name='Užsakovo teisės ir pareigos'),
        ),
        migrations.AlterField(
            model_name='costexpeditionsettings',
            name='payment_terms',
            field=models.TextField(blank=True, default='30 kalendorinių dienų po PVM sąskaitos-faktūros ir važtaraščio su krovinio gavimo data ir gavėjo vardu, pavarde, parašu gavimo.', help_text='Apmokėjimo terminas lietuvių kalba', verbose_name='Apmokėjimo terminas (LT)'),
        ),
        migrations.AlterField(
            model_name='ordersettings',
            name='carrier_obligations',
            field=models.JSONField(blank=True, default=list, help_text='Sąrašas punktų, pvz: [{"text": "...", "text_en": "...", "text_ru": "..."}]', verbose_name='Vežėjo teisės ir pareigos'),
        ),
        migrations.AlterField(
            model_name='ordersettings',
            name='client_obligations',
            field=models.JSONField(blank=True, default=list, help_text='Sąrašas punktų, pvz: [{"text": "...", "text_en": "...", "text_ru": "..."}]', verbose_name='Užsakovo teisės ir pareigos'),
        ),
        migrations.AlterField(
            model_name='ordersettings',
            name='payment_terms',
            field=models.TextField(blank=True, default='30 kalendorinių dienų po PVM sąskaitos-faktūros ir važtaraščio su krovinio gavimo data ir gavėjo vardu, pavarde, parašu gavimo.', help_text='Apmokėjimo terminas lietuvių kalba', verbose_name='Apmokėjimo terminas (LT)'),
        ),
    ]
