# Generated by Django 4.2.7 on 2026-01-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0034_expeditionsettings_carrier_obligations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvmrate',
            name='article_en',
            field=models.CharField(blank=True, default='', help_text='PVM įstatymo straipsnis anglų kalba', max_length=255, verbose_name='Straipsnis (EN)'),
        ),
        migrations.AddField(
            model_name='pvmrate',
            name='article_ru',
            field=models.CharField(blank=True, default='', help_text='PVM įstatymo straipsnis rusų kalba', max_length=255, verbose_name='Straipsnis (RU)'),
        ),
        migrations.AlterField(
            model_name='pvmrate',
            name='article',
            field=models.CharField(blank=True, help_text='PVM įstatymo straipsnis lietuvių kalba (pvz. 5 str. 7 d., 6 str., ir t.t.)', max_length=255, verbose_name='Straipsnis (LT)'),
        ),
    ]
