# Generated by Django 4.2.7 on 2026-01-23 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0035_pvmrate_article_en_pvmrate_article_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAutoStatusSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Jei įjungta, užsakymų statusai bus keičiami automatiškai pagal datas', verbose_name='Įjungti automatinį statusų keitimą')),
                ('auto_new_to_executing', models.BooleanField(default=True, help_text='Kai užsakymas turi pakrovimo ir iškrovimo datas, automatiškai keisti statusą į "Vykdomas"', verbose_name='Automatiškai keisti iš "Naujas" į "Vykdomas"')),
                ('auto_executing_to_waiting', models.BooleanField(default=True, help_text='Kai iškrovimo data praėjo, automatiškai keisti statusą į "Laukiama Dokumentų"', verbose_name='Automatiškai keisti iš "Vykdomas" į "Laukiama Dokumentų"')),
                ('auto_waiting_to_finished', models.BooleanField(default=True, help_text='Kai visi dokumentai gauti ir mokėjimai atlikti, automatiškai keisti statusą į "Baigtas"', verbose_name='Automatiškai keisti iš "Laukiama Dokumentų" į "Baigtas"')),
                ('days_after_unloading', models.IntegerField(default=0, help_text='Kiek dienų po iškrovimo datos keisti statusą į "Laukiama Dokumentų" (0 = tą pačią dieną)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dienų po iškrovimo')),
            ],
            options={
                'verbose_name': 'Užsakymų automatinio statusų keitimo nustatymai',
                'verbose_name_plural': 'Užsakymų automatinio statusų keitimo nustatymai',
            },
        ),
    ]
