# Generated by Django 4.2.7 on 2026-01-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0036_add_order_auto_status_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderautostatussettings',
            name='auto_new_to_executing',
        ),
        migrations.RemoveField(
            model_name='orderautostatussettings',
            name='auto_waiting_to_finished',
        ),
        migrations.AddField(
            model_name='orderautostatussettings',
            name='auto_assigned_to_executing',
            field=models.BooleanField(default=True, help_text='Kai šiandien yra tarp pakrovimo ir iškrovimo datų, automatiškai keisti statusą į "Vykdomas"', verbose_name='Automatiškai keisti iš "Priskirtas" į "Vykdomas"'),
        ),
        migrations.AddField(
            model_name='orderautostatussettings',
            name='auto_finished_to_closed',
            field=models.BooleanField(default=True, help_text='Kai sumokėta visiems vežėjams, automatiškai keisti statusą į "Uždarytas"', verbose_name='Automatiškai keisti iš "Baigtas" į "Uždarytas"'),
        ),
        migrations.AddField(
            model_name='orderautostatussettings',
            name='auto_new_to_assigned',
            field=models.BooleanField(default=True, help_text='Kai užsakymui priskiriamas vežėjas, automatiškai keisti statusą į "Priskirtas"', verbose_name='Automatiškai keisti iš "Naujas" į "Priskirtas"'),
        ),
        migrations.AddField(
            model_name='orderautostatussettings',
            name='auto_payment_to_finished',
            field=models.BooleanField(default=True, help_text='Kai apmokėjimas iš kliento gautas, automatiškai keisti statusą į "Baigtas"', verbose_name='Automatiškai keisti iš "Laukiama Apmokėjimo" į "Baigtas"'),
        ),
        migrations.AddField(
            model_name='orderautostatussettings',
            name='auto_waiting_to_payment',
            field=models.BooleanField(default=True, help_text='Kai visi dokumentai gauti iš vežėjo ir sąskaita išsiųsta užsakovui, automatiškai keisti statusą į "Laukiama Apmokėjimo"', verbose_name='Automatiškai keisti iš "Laukiama Dokumentų" į "Laukiama Apmokėjimo"'),
        ),
        migrations.AlterField(
            model_name='orderautostatussettings',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Jei įjungta, užsakymų statusai bus keičiami automatiškai pagal datas ir kitus kriterijus', verbose_name='Įjungti automatinį statusų keitimą'),
        ),
    ]
