# Generated by Django 4.2.7 on 2026-01-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0037_update_order_auto_status_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAutoStatusRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(help_text='Pradinis statusas', max_length=50, verbose_name='Iš statuso')),
                ('to_status', models.CharField(help_text='Tikslas statusas', max_length=50, verbose_name='Į statusą')),
                ('condition_type', models.CharField(choices=[('carrier_added', 'Atsiranda vežėjas'), ('dates_between', 'Data tarp pakrovimo ir iškrovimo'), ('unloading_passed', 'Iškrovimo data praėjo'), ('docs_received_and_invoice_sent', 'Dokumentai gauti ir sąskaita išsiųsta'), ('client_paid', 'Klientas apmokėjo'), ('carriers_paid', 'Visų vežėjų apmokėjimas gautas')], help_text='Kokia sąlyga turi būti patenkinta', max_length=50, verbose_name='Sąlygos tipas')),
                ('condition_params', models.JSONField(blank=True, default=dict, help_text='Papildomi parametrai sąlygai (pvz., dienų skaičius)', verbose_name='Sąlygos parametrai')),
                ('enabled', models.BooleanField(default=True, help_text='Ar ši taisyklė aktyvi', verbose_name='Įjungta')),
                ('priority', models.IntegerField(default=0, help_text='Kuo didesnis skaičius, tuo aukštesnis prioritetas (pirmiau tikrinama)', verbose_name='Prioritetas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Automatinio statusų keitimo taisyklė',
                'verbose_name_plural': 'Automatinio statusų keitimo taisyklės',
                'ordering': ['-priority', 'from_status'],
            },
        ),
    ]
