# Generated by Django 4.2.7 on 2026-02-04 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0041_invoicesettings_currency_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='body_html',
            field=models.TextField(blank=True, help_text='El. laiško turinys HTML formatu. Naudokite tuos pačius kintamuosius kaip tekste. Jei tuščias, bus naudojamas tekstinis turinys.', verbose_name='Turinys (HTML)'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body_text',
            field=models.TextField(help_text='Kintamieji pagal šabloną. Sąskaita/priminimai: {invoice_number}, {order_number}, {client_order_number}, {partner_name}, {amount}, {amount_net}, {amount_total}, {vat_rate}, {issue_date}, {due_date}, {overdue_days}, {payment_status}, {manager_name}, {other_unpaid_invoices}, {route_from}, {route_to}, {loading_date}, {unloading_date}, {order_date}. Užsakymas klientui/vežėjui: {order_number}, {client_order_number}, {order_date}, {partner_name}, {partner_code}, {partner_vat_code}, {route_from}, {route_to}, {loading_date}, {unloading_date}, {price_net}, {price_with_vat}, {manager_name}; vežėjui dar {expedition_number}.', verbose_name='Turinys (tekstas)'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(help_text='Kintamieji pagal šabloną. Sąskaita/priminimai: {invoice_number}, {order_number}, {client_order_number}, {partner_name}, {amount}, {amount_net}, {amount_total}, {vat_rate}, {issue_date}, {due_date}, {overdue_days}, {payment_status}, {manager_name}, {other_unpaid_invoices}, {route_from}, {route_to}, {loading_date}, {unloading_date}, {order_date}. Užsakymas klientui/vežėjui: {order_number}, {client_order_number}, {order_date}, {partner_name}, {partner_code}, {partner_vat_code}, {route_from}, {route_to}, {loading_date}, {unloading_date}, {price_net}, {price_with_vat}, {manager_name}; vežėjui dar {expedition_number}.', max_length=512, verbose_name='Antraštė'),
        ),
        migrations.AlterField(
            model_name='orderautostatussettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderautostatussettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uisettings',
            name='status_colors',
            field=models.JSONField(blank=True, default=dict, help_text='JSON objektas su spalvomis pagal statusus: {"invoices": {"paid": "#28a745", "not_paid": "#dc3545", ...}, "expeditions": {"new": "#17a2b8", ...}, "orders": {"new": "#17a2b8", ...}, "payment_colors": {"no_invoice": "#000000", "unpaid": "#dc3545", "partially_paid": "#ffc107", "paid": "#28a745"}}', verbose_name='Statusų spalvos'),
        ),
    ]
